techmatters/terraso-web-client

- package-lock.json
update NPM modules using `npm audit fix`.
> chore: update NPM modules using npm audit fix

- README.md
- src/config.js
- src/terrasoBackend/api.js
- Added environment configuration
Fixes #110
> chore: Added environment configuration

- src/auth/components/AccountForm.js
Simplify markup for sign in buttons. Remove extra JSX tag.
> refactor: simplify markup for sign in buttons

- src/account/accountSlice.js
- src/account/auth.js
- src/common/components/AppBar.js
- src/common/components/AppBar.test.js
- src/config.js
- src/state/utils.js
- Added domain to cookie delete
Fixes #120
> Fix: Auth token cookies delete fixed

- src/account/accountSlice.js
- src/account/components/AccountAvatar.js
- src/account/components/AccountProfile.js
- src/account/components/AccountProfile.test.js
- src/account/components/RequireAuth.test.js
- src/common/components/AppBar.js
- src/group/components/GroupList.test.js
- src/group/components/GroupMembershipCard.js
- src/group/components/GroupMembershipCard.test.js
- src/group/groupFragments.js
- Display User profile image
Fixes #123 
Screenshots:
> feat: Display user profile image

- package-lock.json
- package.json
- src/account/accountFragments.js
- src/account/accountService.js
- src/account/accountSlice.js
- src/account/auth.js
- src/account/components/AccountProfile.js
- src/account/components/AccountProfile.test.js
- src/account/components/RequireAuth.test.js
- src/forms/components/Form.js
- src/forms/components/FormField.js
- src/localization/locales/en-US.json
- src/theme.js
- Improvements to avoid using /auth/user endpoint
- Form improvements to have more flexibilty on its structure
- Save user data support
Fixes #126 
Screenshot:
> feat: User profile save

- src/common/components/Table.js
- Removed Table selected count footer
Fixes #124 
Screenshot:
> fix: Removed table selected count

- src/account/auth.js
- src/account/components/RequireAuth.test.js
- src/state/utils.js
- Added code to handle renew token
Fixes #118
> feat: Renew tokens

- src/localization/locales/en-US.json
- src/tool/components/Tool.js
- src/tool/components/ToolList.js
Adds text indicating Kobo will be available in the future. Move Kobo strings out of code an in to i18n JSON.
Fixes #140.
Go to http://127.0.0.1:3000/tools/
> fix: describe Kobo as coming soon

- src/group/components/GroupList.test.js
- src/landscape/components/LandscapeList.test.js
- Fixed tests to gather elements after sort
> fix: Fixed sort list tests

- .eslintrc
- Added missing eslint checks (unused vars, not defined vars, a11y)
> fix: Added missing eslint checks

- src/home/homeService.js
- Updated param for groups relationshp
Fixes #182
> chore: Group param update

- src/account/components/AccountLogin.js
- src/account/components/AccountLogin.test.js
- src/account/components/RequireAuth.js
- src/account/components/RequireAuth.test.js
- src/group/membership/components/GroupMembershipCard.test.js
- Added referrer for login process
Fixes #138 
Screenshot:
> feat: Added referrer for login

- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/navigation/Navigation.js
- src/navigation/Navigation.test.js
- Improved accessibility for main navigation
Fixes #201
> fix: main navigation accessibility improvements

- Makefile
- src/group/components/GroupsHomeCard.js
- src/home/components/HomeCard.js
- src/landscape/components/LandscapesHomeCard.js
- src/tool/components/ToolHomeCard.js
- Improved home lists accessibility
- Added home sections
- Added global lint command
Fixes #202
> fix: Improved accessibility for home lists

- package-lock.json
- package.json
- src/common/components/Table.js
- src/forms/components/FormField.js
- src/group/components/GroupList.js
- src/group/components/GroupList.test.js
- src/group/membership/components/GroupMembersList.js
- src/landscape/components/LandscapeList.js
- src/landscape/components/LandscapeList.test.js
- src/landscape/membership/components/LandscapeMembers.test.js
- src/localization/components/LocalePicker.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- Upgrade dependencies to fix tab issue for data grid
- Fixed locale selector focus style
- Removed empty links in tables
- Added actions column header description
- Added locale selector label
Fixes #204
Fixes #207
Fixes #203 
Screenshots:
> fix: Upgrade dependencies, fixed locale picker, fixed table headers

- src/account/components/AccountProfile.js
- src/common/components/PageHeader.js
- src/forms/components/Form.js
- src/group/components/GroupDefaultHomeCard.js
- src/group/components/GroupForm.js
- src/group/components/GroupView.js
- src/group/components/GroupsHomeCard.js
- src/group/membership/components/GroupMembershipCard.js
- src/landscape/components/LandscapeDefaultHomeCard.js
- src/landscape/components/LandscapeForm.js
- src/landscape/components/LandscapeView.js
- src/landscape/components/LandscapesHomeCard.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/theme.js
- src/tool/components/Tool.js
- src/tool/components/ToolHomeCard.js
- Headers fixes
- Form labels added
- Content sections added
Fixes #206 
Fixes #199 
Fixes #198 
Screenshots:
> fix: accessibility updates for sections, headers and forms

- src/navigation/SkipLinks.js
- Added missing key for skip links
> fix: Added missing key for skip links

- src/group/components/GroupsHomeCard.js
- src/home/components/Home.test.js
- src/home/homeService.js
- src/landscape/components/LandscapesHomeCard.js
- Fixed user memberships for home
Fixes #194 
Screenshot:
> fix: Show correct roles for group memberships on home page

- src/navigation/Navigation.js
- src/navigation/Navigation.test.js
- Allow open in new tab
- Changed navigation buttons to links
- Removed bad aria-attributes and and added aria-current to show current page
Fixes #159 
Screenshot:
> fix: Update navigation links stye and aria attributes

- src/account/accountService.js
- src/account/accountSlice.js
- src/localization/components/LocalePicker.js
- src/localization/components/LocalePicker.test.js
- src/user/userFragments.js
- Save and use language preference
Fixes #185
> feat: Save language preference

- src/navigation/Navigation.js
- src/theme.js
- Fixed Navigation color contrast
- Fixed avatar color contrast
Fixes #234 
Screenshots:
> Fix: color contrast

- src/account/accountService.js
- src/account/components/AccountProfile.test.js
- Omit preferences when users saves profile
Fixes #245
> fix: Omit preferences on user profile save

- src/common/components/Table.js
- Show actions column header
Fixes #235 
Screenshots:
> fix: Show actions column header

- src/account/components/AccountAvatar.js
- src/account/components/AccountProfile.js
- src/account/components/AccountProfile.test.js
- src/localization/components/LocalePicker.test.js
- Added img role to avart component
Fixes #236 
Screenshot:
> fix: Added img role to avatar

- package-lock.json
This change only bump dependencies versions.
> chore: update dependencies versions

- src/forms/components/Form.js
- src/localization/locales/en-US.json
- Fixed typo
- Fixed form button order
Fixes #255 
Fixes #261
> fix: Fixed typo, correct buttons order

- src/landscape/components/LandscapeBoundaries.js
- src/landscape/components/LandscapeBoundaries.test.js
- Removed duplicated error message
Fixes #263
> fix: Removed duplicated error message

- public/index.html
Add a meta description for the Terraso app. Replace the default React placeholder text.
Fixes #257.
Open index page of app. View source.
> fix: add meta description for Terraso app

- src/common/components/Footer.js
- src/index.js
- src/navigation/Navigation.js
- Fixed footer position
Fixes #220
> fix: Fixed footer position

- public/index.html
- -Defered google fonts load
Fixes #195
> fix: Defered google fonts

- README.md
- src/config.js
- Fixed Contact form environment variables name
> fix: Fixed contact form env variables

- src/account/accountService.js
- src/account/components/AccountProfile.js
- src/account/components/AccountProfile.test.js
- src/forms/components/FormField.js
- src/landscape/components/LandscapeForm.js
- src/landscape/components/LandscapeForm.test.js
- src/localization/components/LocalePicker.js
- src/localization/components/LocalePickerSelect.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- Added language field to user profile
Fixes #233
> feat: Added language to profile

- src/landscape/components/LandscapeBoundaries.js
- src/landscape/components/LandscapeBoundaries.test.js
- src/landscape/landscapeUtils.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/monitoring/logger.js
Improves error handling for GeoJSON boundary uploading. Shows more granular errors, refactors code and adds more tests.
> fix: improve error handling for GeoJSON boundary uploading

- src/account/accountService.js
- src/account/accountSlice.js
- src/account/components/RequireAuth.test.js
- src/common/components/AppBar.test.js
- On sign out call API to end the user session
Fixes #281
> feat: API logout

- public/index.html
Remove boilerplate comments from index.html template.
> chore: remove comments from template

- package-lock.json
- package.json
- src/gis/components/Map.css
- src/gis/components/Map.js
- src/landscape/components/LandscapeMap.js
Add a search box to map component. When a location is found, a draggable pin is inserted.
Fixes #299.
> feature: add search to map component

- .github/workflows/codeql-analysis.yml
> feat: GitHub CodeQL scan

- package-lock.json
- package.json
- src/custom-hooks.js
- src/gis/components/Map.js
- src/landscape/components/LandscapeForm/BoundaryStep.js
- src/landscape/components/LandscapeForm/LandscapeFormPin.test.js
- src/landscape/components/LandscapeMap.js
> fix: Drop pin on landscape creation

- src/common/utils.js
- src/landscape/components/LandscapeForm/BoundaryStep.js
- src/landscape/components/LandscapeForm/InfoStep.js
- src/landscape/components/LandscapeView.js
Menu width now full-size on mobile.
When no country is selected, placeholder item is shown.
> fix: improve country menu popup

- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
Link to the main Terraso website from the app.
Fixes #354.
> feat: add About link to footer

- src/group/components/GroupView.js
- src/group/groupSlice.js
- src/group/membership/components/GroupMembershipJoinLeaveButton.js
- src/index.js
- src/landscape/components/LandscapeView.js
- src/landscape/components/LandscapeView.test.js
- src/landscape/landscapeSlice.js
- src/layout/AppWrappers.js
- src/layout/RefreshProgressProvider.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/tests/utils.js
Update landscape/group profile on membership status change
Fixes #344
> feat: Update landscape/group profile on membership status change

- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/sharedData/components/SharedDataEntry.js
> fix: Shared data A11y fixes

- src/group/groupFragments.js
Removes slug from DataEntryNode query.
Backend issue: https://github.com/techmatters/terraso-backend/pull/177
> fix: remove slug from DataEntryNode query

- src/common/components/SocialShare.js
Increase width of social share dialog with MUI attributes/properties.
Fixes #369.
> fix: use MUI properties to set share dialog width

- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- Updated Shared data help link
> fix: Updated shared data help links

- src/account/components/AccountProfile.js
- src/config.js
- src/group/components/GroupForm.js
- src/landscape/components/LandscapeForm/InfoStep.js
- src/sharedData/components/SharedDataUpload.js
Remove leading and trailing whitespace from text fields during validation.
Fixes #371.
> fix: trim text fields during validation

- src/sharedData/components/SharedDataCard.js
- src/sharedData/components/SharedDataEntry.js
- Fixed broken strings for shared data
> fix: Fixed shared data broken strings key

- src/gis/components/Map.css
- src/gis/components/Map.js
Ensure drop pin tool appears on mobile
Fixes #360.
> fix: ensure drop pin tool appears on mobile

- src/sharedData/components/SharedDataEntry.js
- src/sharedData/components/SharedDataUpload.js
adds event tracking to file upload, download, delete and edit (rename/update description).
Fixes #408.
> feat: add tracking to shared file events

- src/group/groupService.js
- src/group/membership/components/GroupMembers.js
- src/home/homeService.js
- src/landscape/components/LandscapeView.test.js
- src/landscape/landscapeFragments.js
- src/landscape/landscapeService.js
- src/landscape/membership/components/LandscapeMembers.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/permissions/components/Restricted.js
- src/permissions/index.js
- src/sharedData/components/SharedDataCard.js
- src/sharedData/sharedDataService.js
- src/sharedData/sharedDataSlice.js
> fix: Fetch data entries separately

- src/group/components/GroupList.js
- src/group/components/GroupList.test.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- Removed members count in group directory
- Increased actions column width
Fixes #424
> feat: Restrict membership: group directory update

- src/group/components/GroupView.js
- src/group/membership/components/GroupMembershipCard.js
- src/group/membership/components/GroupMembershipCard.test.js
- src/group/membership/components/GroupMembershipInfo.js
- src/landscape/membership/components/LandscapeMembers.test.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/permissions/rules.js
- Added different content for closed groups in members card
- Added manage members button
- Added info button to grup members card
Fixes #425 
Fixes #423
> feat: restrict membership group profile

- src/group/components/GroupsHomeCard.js
- src/home/components/Home.test.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- Added pending groups to user home page
Fixes #427
> feat: Restrict membership - member pending home page

- src/group/components/GroupList.js
- src/group/components/GroupList.test.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- Improved no groups message
Fixes #420
> fix: Improved no groups message

- src/landscape/components/LandscapeList.js
- src/landscape/components/LandscapeList.test.js
- src/landscape/components/LandscapeListMap.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
> feat: Added map to landscapes directory

- package-lock.json
- package.json
- src/landscape/components/LandscapeList.js
- src/landscape/components/LandscapeList.test.js
- src/landscape/components/LandscapeListMap.css
- src/landscape/components/LandscapeListMap.js
- src/landscape/landscapeService.js
- src/landscape/landscapeUtils.js
- Display landscapes markers
- Display landsacpes clusters
Fixes #446
> feat: Explorable map of landscapes: Display points and clusters

- src/landscape/components/LandscapeList.test.js
- src/landscape/components/LandscapeListMap.css
- src/landscape/components/LandscapeListMap.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/theme.js
- Added popup when clicking on landscape pin in map
Fixes #447
> feat: Explorable map of landscapes - Pin popup

- .github/workflows/build.yml
- .github/workflows/check-commits.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/localization.yml
- package-lock.json
- package.json
- src/landscape/components/LandscapeList.js
- src/landscape/components/LandscapeList.test.js
- src/landscape/components/LandscapeListMap.css
- src/landscape/components/LandscapeListMap.js
- src/landscape/landscapeService.js
- src/landscape/landscapeUtils.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/theme.js
Fixes #445 
Fixes #446 
Fixes #445
> feat: Explorable map of landscapes (complete feature)

- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/navigation/Navigation.js
Improves the accessibility of the main site navigation.
Fixes #467.
> fix: improve accessibility of main navigation

- src/contact/ContactForm.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
Added descriptive title for Contact page. 
Fixes #476 
Go to /contact
> fix: descriptive title for Contact page

- .github/workflows/build.yml
- .github/workflows/check-commits.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/localization.yml
- src/gis/components/Map.js
- src/landscape/components/LandscapeBoundaries.js
- src/landscape/components/LandscapeBoundariesUpdate.js
- src/landscape/components/LandscapeBoundariesUpdate.test.js
- src/landscape/components/LandscapeForm/BoundaryStep.js
- src/landscape/components/LandscapeMap.js
- src/landscape/components/LandscapeNew.js
- src/landscape/components/LandscapeNewFormGeoJson.test.js
- src/landscape/components/LandscapeNewFormPin.test.js
- src/landscape/components/LandscapeView.js
- src/landscape/landscapeService.js
- src/landscape/landscapeUtils.js
- src/landscape/landscapeUtils.test.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- Added boundary creation options to update boundary page
Fixes #461
> feat: Reused landscape creation boundary options in update boundary

- src/common/components/ConfirmationDialog.js
- src/common/components/SocialShare.js
- src/group/components/GroupsHomeCard.js
- src/landscape/components/LandscapeForm/BoundaryStep.js
- src/landscape/components/LandscapeForm/InfoStep.js
- src/landscape/components/LandscapeNew.js
- src/landscape/components/LandscapesHomeCard.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
Make share dialog and landscape markup more accessible.
Fixes #495.
> fix: make markup of share dialog and landscape more accessible

- src/landscape/components/LandscapeForm/BoundaryStep.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
Add an aria-label to the landscape map (creating and editing a map).
Fixes ##516.
> fix: add aria label to landscape map

- src/layout/PageContainer.js
Remove live region from page container.
Fixes #514.
> fix: remove live region from page container

- src/common/components/Table.js
- src/common/components/TableResponsive.js
- src/group/components/GroupList.js
- src/landscape/components/LandscapeList.js
Provide a description of the grid to screen reader users.
Fixes #505.
> fix: add aria-labelledby to group and landscape grids

- src/group/components/GroupDefaultHomeCard.js
- src/group/components/GroupsHomeCard.js
- src/group/membership/components/GroupMembershipCard.js
- src/landscape/components/LandscapeDefaultHomeCard.js
- src/landscape/components/LandscapesHomeCard.js
- src/tool/components/Tool.js
* Repeated Consecutive Links
* Inclusion of Decorative Separator for Screen Reader Users
* Problematic Implementation of Link as Button
Fixes #501.
> fix: improve markup for separators and links

- src/common/components/ConfirmationDialog.js
Set initial focus and aria-describedby for confirmation dialogs
Fixes #499.
> fix: Set initial focus and describedby for confirmation dialogs

- src/common/components/Table.js
- src/group/components/GroupList.js
- src/group/components/GroupView.js
- src/group/components/GroupsHomeCard.js
- src/landscape/components/LandscapeList.js
- src/landscape/components/LandscapesHomeCard.js
- src/layout/Footer.js
- src/theme.js
underline links on hover and focus so color isn't the only distinguishing characteristic.
Fixes #512.
> fix: underline links on hover and focus

- package-lock.json
- package.json
- src/account/components/AccountAvatar.js
- src/common/components/Stepper.js
- src/group/membership/components/GroupMembersList.js
- src/group/membership/components/GroupMembershipCard.js
- src/landscape/components/LandscapeNew.js
Add semantic markup (lists) for Stepper steps and Group/Landscape members.
Fixes #520.
> fix: add list structure for steps and members

- src/index.css
- src/theme.js
Disable the ripple animation and use a consistent focus indicator on all controls.
Fixes #524.
> fix: consistent focus indicator

- package-lock.json
- package.json
- src/gis/gisUtils.js
- src/landscape/components/LandscapeListMap.js
- src/landscape/landscapeUtils.js
- Normalized longitude value
Fixes #533
> fix: Normalized lng coordinate for landscape maps

- src/gis/components/Map.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
Add aria-label attributes to the map search box and clear search button.
Fixes #529. Fixes #531.
> fix: add aria label to map search box

- src/account/components/AccountAvatar.js
- src/group/membership/components/GroupMembershipCard.js
- Improved Trans component values if used with Typography MUI component
- Added Avatar validation for allowed props 
Fixes #497 
Fixes #466
> fix: Improved Trans values and MUI Avatar allowed props validation

- src/account/components/AccountProfile.test.js
- Fixed Account Profile Avatar test
Fixes #538
> fix: Verify no image is displayed in avatar

- package-lock.json
- package.json
- src/common/components/DropZone.js
- src/sharedData/components/SharedDataEntry.js
- src/sharedData/visualization/components/VisualizationConfigForm/SelectDataFileStep.js
update filesize npm module to v10.
> fix: update filesize to v10

- package-lock.json
- package.json
update @mui/x-data-grid npm module to 5.17.5
> chore: update @mui/x-data-grid to 5.17.5

- src/landscape/components/LandscapeBoundariesUpdate.js
- src/landscape/components/LandscapeForm/Actions.js
- src/landscape/components/LandscapeForm/AffiliationStep.js
- src/landscape/components/LandscapeForm/BoundaryStep.js
- src/landscape/components/LandscapeForm/InfoStep.js
- src/landscape/components/LandscapeForm/ProfileStep.js
- src/landscape/components/LandscapeNew.js
> feat: Added profile and affiliation step to new form

- src/group/components/GroupForm.js
- src/home/components/Home.js
- src/landscape/components/LandscapeBoundariesUpdate.js
- src/landscape/components/LandscapeForm/BoundaryStep.js
- src/landscape/components/LandscapeNew.js
- src/sharedData/visualization/components/VisualizationConfigForm/PreviewStep.js
- src/tool/components/Tool.js
This will add the Plausible changes to master.
Using the Plausible interface, I can see that all of expected events are being tracked on staging.
Fixes #488 
Fixes #518 
Fixes #490 
Fixes #491 
Fixes #492
> feat: Merge plausible changes to main

- src/landscape/components/LandscapeNew.js
- Create Landscape after step 1
> feat: Create Landscape after step 1

- src/landscape/components/LandscapeForm/Actions.js
- src/landscape/components/LandscapeForm/KeyInfoStep.js
- Fixed updated buttons position
> fix: Fixed updated buttons position

- src/common/utils.js
- src/landscape/components/LandscapeForm/BoundaryStep.js
- src/landscape/components/LandscapeForm/InfoStep.js
- src/landscape/components/LandscapeSharedDataUpload.js
- src/landscape/components/LandscapeSharedDataVisualizationConfig.test.js
- src/navigation/scrollTo.js
- src/sharedData/components/SharedDataCard.js
> feat: ScrollTo component

- src/gis/components/Map.js
- src/landscape/components/LandscapeForm/BoundaryStep.js
- src/landscape/components/LandscapeMap.js
> feat: prop for map default layer

- src/common/components/InlineHelp.js
- src/landscape/components/LandscapeView.js
- src/landscape/components/LandscapeView.test.js
- src/landscape/landscapeUtils.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/theme.js
- Added Landsacpe boundary download button
Fixes #605
> Feat: Landscape download boundary

- src/group/components/GroupSharedDataUpload.test.js
- src/landscape/components/LandscapeSharedDataVisualization.test.js
- src/landscape/components/LandscapeSharedDataVisualizationConfig.test.js
Use the correct MIME type for CSVs in tests.
> fix: use correct MIME type for CSVs

- src/landscape/components/LandscapeProfile/ProfileCard.js
- src/landscape/landscapeFragments.js
- src/localization/locales/en-US.json
Adds the Area field to the Landscape Profile
> feat: add area to landscape profile

- src/localization/locales/en-US.json
We want to point to the Privacy Policy as there isn't a Terms of Service to reference yet.
Fixes #600
- Open frontend
> fix: update English text to point to Privacy Policy

- src/landscape/components/LandscapeForm/AffiliationStep.js
- src/landscape/components/LandscapeForm/ProfileStep.js
- src/landscape/landscapeUtils.js
Fixes text in Landscape status option
> fix: Change text format of the LP question

- src/landscape/components/LandscapeForm/AffiliationUpdate.js
- src/landscape/components/LandscapeForm/BoundaryStepUpdate.js
- src/landscape/components/LandscapeForm/DevelopmentStrategyUpdate.js
- src/landscape/components/LandscapeForm/KeyInfoUpdate.js
- src/landscape/components/LandscapeForm/New.js
- src/landscape/components/LandscapeForm/ProfileUpdate.js
- src/landscape/components/LandscapeProfile/DevelopmentStrategyCard.js
- src/landscape/landscapeService.js
- src/landscape/landscapeSlice.js
- src/localization/locales/en-US.json
- Improved update/save messages
> fix: Improved update messages

- src/taxonomies/components/TaxonomyAutocomplete.js
The suggestion comes at the end now
> fix: change multiselect add order

- src/landscape/components/LandscapeForm/ProfileImageStep.js
- src/landscape/components/LandscapeProfile/ProfileCard.js
- src/landscape/landscapeFragments.js
- src/landscape/landscapeService.js
- Just send landscape data needed to update
- Avoid fetching areaPolygon everytime
- Set image to save on change in crop tool
> fix: Landscape profile image fixes

- src/landscape/components/LandscapeForm/New.js
- src/landscape/landscapeService.js
- Get landscape profile fields after creation and update
> fix: Get landscape profile fields after creation and update

- src/landscape/components/LandscapeProfile/ProfileCard.js
Localize population number (add commas).
Fixes #626.
> fix: localize population number (add commas)

- src/account/accountService.js
- src/group/groupFragments.js
- src/group/groupService.js
- src/landscape/components/LandscapeForm/AffiliationStep.js
- src/landscape/components/LandscapeForm/AffiliationUpdate.test.js
- src/landscape/components/LandscapeForm/ProfileStep.js
- src/landscape/components/LandscapeForm/ProfileUpdate.test.js
- src/landscape/components/LandscapeProfile/AffiliationCard.js
- src/landscape/components/LandscapeProfile/ProfileCard.js
- src/landscape/landscapeService.js
- src/sharedData/sharedDataService.js
- src/taxonomies/taxonomiesConstants.js
- src/taxonomies/taxonomiesService.js
- src/terrasoBackend/api.js
- Changed error handling for API errors
- Change graph QL ENUM usage
- https://github.com/techmatters/terraso-backend/pull/242
Fixes #....
> chore: graphql upgrade compatibility

- src/landscape/components/LandscapeForm/ProfileUpdate.test.js
- src/terrasoBackend/api.js
- src/terrasoBackend/api.test.js
- Check if errors data is empty
- Added mutation errors tests
> fix: graph ql error condition

- package-lock.json
- package.json
- src/account/accountSlice.js
- src/group/groupSlice.js
- src/group/membership/components/GroupMembershipJoinLeaveButton.js
- src/home/homeSlice.js
- src/landscape/landscapeSlice.js
- src/notifications/notificationsSlice.js
- src/sharedData/sharedDataSlice.js
- src/taxonomies/taxonomiesSlice.js
- Upgraded redux toolkit
- Change extraReducers strcuture to use builder
> chore: redux toolkit upgrade

- src/common/components/TableResponsive.js
- src/landscape/components/LandscapeList.test.js
- Updated logic to clear URL params on clear search
Fixes #656
> fix: Table clear search fix

- src/landscape/components/LandscapeForm/ProfileUpdate.test.js
- src/landscape/landscapeService.js
- Send int explicitly for int graph QL params
Fixes #....
> fix: Graph QL upgrade bugs

- src/landscape/components/LandscapeForm/ProfileStep.js
avoid nesting <p> tags; use default font stack for ecosystem helper text
> fix: avoid nesting <p> tags; use default font stack for ecosystem help

- src/config.js
> fix: Split map accepted types

- .github/workflows/build.yml
- .github/workflows/localization.yml
- Dockerfile
> chore: update node to 18.13

- Dockerfile
chore: update node to 18.14 in Dockerfile.
> chore: update node to 18.14 in Dockerfile

- src/group/components/GroupSharedDataUpload.js
- src/landscape/components/LandscapeForm/BoundaryStepUpdate.js
- src/landscape/components/LandscapeForm/New.js
- src/landscape/components/LandscapeSharedDataUpload.js
- src/monitoring/ilm.js
- src/sharedData/components/SharedDataUpload/index.js
- src/sharedData/visualization/components/VisualizationConfigForm/PreviewStep.js
- Added ILM output for plausible events
Fixes #672
> feat: Added ILM Output to plausible events

- src/home/components/Home.test.js
- src/home/homeService.js
- src/navigation/components/Routes.js
- src/storyMap/components/StoryMapNew.js
- src/storyMap/components/StoryMapUpdate.js
- src/storyMap/components/StoryMapsHomeCard.js
- src/storyMap/components/StoryMapsToolHome.js
- src/storyMap/components/UserStoryMap.js
- src/storyMap/storyMapFragments.js
- src/storyMap/storyMapService.js
- src/storyMap/storyMapUtils.js
- Added story map url identifier, this removes the need to validate the uniqueness for the title
Fixes #751
> feat: Added story map url identifier

- src/account/accountSlice.js
- src/account/components/AccountProfile.js
- src/account/components/AccountProfile.test.js
- src/account/components/Unsubscribe.js
- src/account/components/Unsubscribe.test.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/navigation/components/Routes.js
- src/storyMap/components/StoryMapForm.test.js
Add a setting to enable and disable email notifications. Handle unsubscribe links.
> feat: Email notifications

- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/storyMap/components/StoryMapForm.test.js
- src/tool/components/ToolDefaultCard.js
Remove external link icon from Story Maps on tool page
Fixes #821.
View https://app.staging.terraso.net/tools
> fix: remove external link icon from Story Maps on tool page

- package-lock.json
Update caniuse data. Avoids warnings (and gives us better data).
> chore: update caniuse data

- src/account/accountService.js
- src/account/accountSlice.js
- src/account/components/AccountProfile.js
- src/account/components/AccountProfile.test.js
- src/account/components/Unsubscribe.js
- src/account/components/Unsubscribe.test.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/navigation/components/Routes.js
Add one-click unsubscribe for logged-out users / add token support to unsubscribe links.
Fixes https://github.com/techmatters/terraso-web-client/issues/837 Fixes #839
Depends on https://github.com/techmatters/terraso-backend/pull/379
Backend work: https://github.com/techmatters/terraso-backend/pull/399
> feat: Add one-click unsubscribe for logged-out users / add token support

- package-lock.json
- package.json
We depend on the UI library [emotion](https://emotion.sh) in our `package.json` but do not use it in our project (as far as I can tell), this PR removes the dependency.
> chore: remove unused dependency on @emotion

- Makefile
- README.md
the README says to run the command `build` to build the app for production release, when the correct command is `create-build`
> build: change create-build command to build in Makefile

- src/App.js
- src/app.test.js
- src/common/components/Table.js
- src/index.js
- src/landscape/components/LandscapeListMap.js
- src/landscape/components/LandscapeMapEmbed.js
- src/navigation/components/Routes.js
Create `/landscapes/map` and make it accessible without authentication.
Fixes #478.
Depends on #857 (and https://github.com/techmatters/terraso-backend/pull/418)
> feat: Embeddable landscape map

- src/landscape/components/LandscapeProfile/index.js
Add `og:image` for landscape profiles
> fix: add og:image for landscape profiles

- Dockerfile
> chore: update node to 18.16

- src/common/components/RichTextEditor/index.js
- src/common/components/RichTextEditor/utils.js
- src/common/document.js
- src/storyMap/components/UserStoryMap.js
Add og:description to storymaps. Use chapter 1 text. Use storymap title if no chapter 1 text present.
> fix: storymap og:description

- src/common/components/SocialShare.js
- src/forms/components/Form.js
- src/index.css
- src/landscape/components/LandscapeForm/BoundaryStepBoundariesFile.js
- src/landscape/components/LandscapeForm/KeyInfoStep.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/navigation/components/SkipLinks.css
- src/sharedData/components/SharedDataUpload/index.js
- src/sharedData/visualization/components/VisualizationConfigForm/ColumnSelect.js
- src/sharedData/visualization/components/VisualizationConfigForm/SetDatasetStep.js
- Added selected file message in landscape boundary upload file
- Added separe success message for share copy url
- Focus on first input after form validation
- Added alrt role for share data summary
Airtable:
- [Missing Screen Reader Feedback for Updated Boundaries](https://airtable.com/appGFQz3URVU5GgXt/tblsA2qhrnKiImmOl/viwwZCSHVM5CZkPHM/recgFfuTMPKA5M4Tz?blocks=hide)
- [Missing Screen Reader Feedback for Dynamic Label](https://airtable.com/appGFQz3URVU5GgXt/tblsA2qhrnKiImmOl/viwwZCSHVM5CZkPHM/rec3nVMBUQKw8cP7j?blocks=hide)
- [Landscape Details Form: Missing Screen Reader Feedback on Invalid Submission](https://airtable.com/appGFQz3URVU5GgXt/tblsA2qhrnKiImmOl/viwwZCSHVM5CZkPHM/recatMcREe68a9m2I?blocks=hide)
- [Missing Announcement for Error …
> fix: Screen reader feedback fixes

- src/landscape/components/LandscapeListMap.js
Default landscape list map to satellite view
Fixes #886.
> fix: default landscape list map to satellite view

- src/landscape/components/LandscapeListMap.css
Restore secondary background color on map clusters
> fix: restore background color on map clusters

- src/common/components/RichTextEditor/index.js
- src/storyMap/components/StoryMap.css
- Fixed title and subtile css
- Fixed Button tooltip error
Fixes #796
> fix: Story map titles fixes, and tooltip fixes

- src/account/components/AccountLogin.js
- src/common/components/DropZone.js
- src/common/components/LoaderCard.js
- src/common/components/TableResponsive.js
- src/common/components/UnexpectedError.js
- src/group/components/GroupDefaultHomeCard.js
- src/group/components/GroupForm.js
- src/group/components/GroupList.js
- src/group/components/GroupView.js
- src/group/components/GroupsHomeCard.js
- src/group/membership/components/GroupMembers.js
- src/group/membership/components/GroupMembershipCard.js
- src/landscape/components/LandscapeDefaultHomeCard.js
- src/landscape/components/LandscapeList.js
- src/landscape/components/LandscapesHomeCard.js
- src/landscape/membership/components/LandscapeMembers.js
- src/layout/PageHeader.js
- src/localization/components/LocalePickerSelect.js
- src/navigation/components/Navigation.js
- src/tool/components/ToolCard.js
Replaced `theme.spacing(XYZ)` with `XYZ` in codebase
Fixes #931
> fix: replace theme.spacing(XYZ) with XYZ

- src/storyMap/components/StoryMap.js
- src/storyMap/components/StoryMapForm/EditableMedia.js
Remove deprecated `frameborder` attribute.
> fix: remove deprecated frameborder attribute

- Dockerfile
- scripts/docker/run.sh
- Added python and make to docker image
> fix: Fixed docker env with python and make support

- src/common/components/RichTextEditor/utils.js
- src/storyMap/components/StoryMap.js
- src/storyMap/components/StoryMapForm/ChapterForm.js
- Improved Richtext editor serialization validation
- Added root param to storymap scroller to fix issue for iframes, the issue is happening because scrollama is not able to identify the sections of the story map that are viewable inside the iframe without the explicit link to the document element
> fix: Story chapter height inside iframe

- src/gis/components/MapboxGeocoder.js
- src/storyMap/components/StoryMapForm/MapLocationDialog.js
- Removed geocoder marker
- Fixed geocoder css dependency location
Fixes #771
> fix: Removed geocoder marker

- src/home/components/HomeCard.js
- src/landscape/components/LandscapeDefaultHomeCard.js
- src/landscape/components/LandscapesHomeCard.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
Add landscape home card  icon button and popover
https://github.com/techmatters/terraso-web-client/issues/1004
1. Go to Home page
2. Click on icon button 
3. View popover content:
> feat: landscape home card popover using helperText

- src/home/components/HomeCard.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/storyMap/components/StoryMapsHomeCardDefault.js
Add a caption to story maps homecard image
Fixes #1005
1. Go to home screen
> feat: add caption to story maps home card img

- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
Add spanish translation for "Rocky Hill's Story Map" (Story map home card image caption)
> fix: add spanish translation and change apostrophe

- Dockerfile
> chore: update node to 18.16.1

- docs/typescript-usage.md
> docs: add TypeScript usage docs

- Makefile
- package.json
separate formatting and linting commands
* npm run lint-js
* npm run format-js
* npm run lint-css
* npm run format-css
> chore: separate formatting and linting commands

- src/config.ts
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/storyMap/components/StoryMap.js
- src/storyMap/components/StoryMapForm.test.js
- src/storyMap/components/StoryMapForm/EditableMedia.js
Add a media validation check to handle_config_media to 
https://github.com/techmatters/terraso-backend/pull/606
https://github.com/techmatters/terraso-product/issues/145
1. On homepage, click on "Create New Story Map"
2. Add a title and click on "Add new chapter"
3. Click on "Add Media" and upload a mp4 file
4. Click "Publish" and should be successful
> feat: allow mp4 uploads to storymaps

- .prettierrc
- package-lock.json
- package.json
- src/sharedData/visualization/visualizationMarkers.js
updates prettier to version 3.0.0
> chore: update prettier to version 3.0.0

- src/common/components/SocialShare.js
- Added social share plausible event
Fixes #995
> feat: Social share plausible event

- package-lock.json
- package.json
- src/forms/components/FormField.js
- src/gis/components/MapExport.js
- src/gis/components/MapboxConstants.js
- src/gis/components/MapboxMap.js
- src/gis/components/MapboxMapStyleSwitcher.js
- src/landscape/components/LandscapeList.test.js
- src/landscape/components/LandscapeListMap.js
- src/landscape/components/LandscapeSharedDataVisualization.test.js
- src/landscape/components/LandscapeSharedDataVisualizationConfig.test.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/react-hoc.js
- src/sharedData/sharedDataFragments.ts
- src/sharedData/visualization/components/Visualization.css
- src/sharedData/visualization/components/Visualization.js
- src/sharedData/visualization/components/VisualizationConfigForm/PreviewStep.js
- src/sharedData/visualization/components/VisualizationConfigForm/VisualizationPreview.js
- src/sharedData/visualization/components/VisualizationConfigForm/VisualizeStep.js
- src/sharedData/visualization/components/VisualizationWrapper.js
- src/sharedData/visualization/visualizationContext.js
- src/sharedData/visualization/visualizationMarkers.js
- src/storyMap/components/StoryMap.js
- src/storyMap/components/StoryMapForm.test.js
- src/theme.js
Data maps mapbox migration
Fixes #816 
https://github.com/techmatters/terraso-backend/pull/617
> feat: Data maps mapbox migration

- src/localization/locales/en-US.json
Fixed partnership typo
Fixes #1068
> fix: Fixed partnership typo

- src/common/components/RichTextEditor/index.js
- src/storyMap/components/StoryMap.js
- src/storyMap/components/StoryMapForm/EditableMedia.js
- Enable full screen for embedded videos
- Fixes error with markup in rich text editor placeholder
Fixes https://github.com/techmatters/terraso-product/issues/135
> fix: story map embed and richtext editor fixes

- src/group/membership/components/GroupMembershipCard.js
- src/group/membership/components/GroupMembershipCount.js
- src/group/membership/components/GroupMembershipJoinLeaveButton.js
Fixed redux selector inconsistency
> fix: Fixed redux selector inconsistency

- .github/workflows/build.yml
- .npmcheckrc
- package-lock.json
- package.json
Add a GitHub Actions workflow to check for unused/missing NPM modules with `npm-check`.
Shared client: https://github.com/techmatters/terraso-client-shared/pull/42
> feat: add workflow to check for unused/missing NPM modules

- src/sharedData/visualization/components/VisualizationConfigForm/SetDatasetStep.js
- src/sharedData/visualization/components/VisualizationConfigForm/SetDatasetStep.test.js
Fixed automatic selection of latitude and longitude columns, there was an issue with the column index handled as a falsy value
Fixes #1034
> fix: Data map latitude and longitude auto select

- README.md
Update tool versions in readme (Docker, Node, NPM).
> docs: update tool versions in readme

- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
Added localized value for decription field and improved characters validation message
Fixes #1080
> fix: Added localized value for decription field and improved characters validation message

- src/landscape/components/LandscapeSharedDataVisualization.test.js
- src/sharedData/visualization/components/Visualization.js
- src/sharedData/visualization/components/VisualizationConfigForm/PreviewStep.js
- Removed max zoom when changing bounds
Fixes #1117
> fix: data map bounds fixes

- src/account/components/AccountProfile.js
- src/account/components/AccountProfile.test.js
- src/localization/locales/en-US.json
Add story map notifications preference. Refactor to reused code for group notifications / story map notifications.
> fix: add story map notifications preference

- src/storyMap/components/StoryMapForm/ChaptersSideBar.js
- src/storyMap/components/StoryMapsCard.js
- Removed duplicated button element for story map chapters
- Handle delete callback for story map deletions from list component
> fix: Fixes indentified with E2E tests

- src/storyMap/components/StoryMapForm/ShareDialog.js
- src/storyMap/components/StoryMapInvite.js
- src/storyMap/components/StoryMapInvite.test.js
- src/storyMap/components/StoryMapUpdate.test.js
- src/storyMap/components/StoryMapsCard.js
- src/storyMap/components/StoryMapsToolHome.test.js
Added plausible events for:
- storymap.share.invite
- storymap.share.remove
- storymap.share.accept
Fixes https://github.com/techmatters/terraso-product/issues/390
> feat: Added Story Map collaboration events

- src/storyMap/components/StoryMapForm/index.js
Added event to track story maps chapter move
Fixes #1185
> feat: Added event to track story maps chapter move

- src/account/components/AccountProfile.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
Added notify me when label in account profile
Fixes https://github.com/techmatters/terraso-product/issues/392
> fix: Added notify me when label

- src/common/components/CardActionRouterLink.js
- src/home/components/HomeCard.js
- src/storyMap/components/StoryMapNew.js
- src/storyMap/components/StoryMapsCard.js
- src/storyMap/components/StoryMapsHomeCardDefault.js
- src/storyMap/components/StoryMapsToolHome.js
- Added property to track new story map source
Fixes #1184
> feat: Track new story source

- package-lock.json
- package.json
- src/account/components/AccountLogin.js
- src/account/components/AccountLogin.test.js
- src/account/components/RequireAuth.js
- src/account/components/RequireAuth.test.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/navigation/components/Routes.js
- src/navigation/navigationUtils.js
- src/storyMap/components/StoryMapInvite.js
- src/storyMap/components/StoryMapInvite.test.js
- src/storyMap/storyMapSlice.js
- Added error message when user can't approve membership
Fixes #1196 
- https://github.com/techmatters/terraso-client-shared/pull/114
- https://github.com/techmatters/terraso-backend/pull/858
> fix: Added error message when user can't approve membership

- src/common/components/UserEmailAutocomplete.js
- src/landscape/components/LandscapeForm/KeyInfoStep.js
Use email input type for all email address fields. Fixes:
* story map invite
* landscape profile
> fix: Use email input type for all email address fields

- package-lock.json
- package.json
> chore: update UUID and stylelint

- package-lock.json
- package.json
> chore: bump slate-react from 0.99.0 to 0.100.0

- package-lock.json
- package.json
Bump @hookform/resolvers from 3.3.1 to 3.3.2.
> build: bump @hookform/resolvers from 3.3.1 to 3.3.2

- package-lock.json
- package.json
Bump @reduxjs/toolkit from 1.9.5 to 1.9.7.
> build: bump @reduxjs/toolkit from 1.9.5 to 1.9.7

- src/group/components/GroupSharedDataUploadFiles.test.js
- src/sharedData/components/SharedDataUpload/index.js
Added file size and type to plausible event
Fixes #1218
> feat: Added file size and type to plausible event

- package-lock.json
- package.json
- src/gis/gisUtils.js
- src/landscape/components/LandscapeListMap.js
Moves isValidLatitude and isValidLongitude to client-shared.
> Chore: move lat/lon checks to client-shared

- package-lock.json
- package.json
Bump @testing-library/jest-dom from 5.17.0 to 6.1.4.
> build: bump @testing-library/jest-dom from 5.17.0 to 6.1.4

- src/sharedData/visualization/components/VisualizationWrapper.js
Track map PNG downloads
Fixes #1272.
> fix: track map PNG downloads

- src/collaboration/components/MembershipCard.js
- src/group/components/GroupSharedDataVisualizationConfig.js
- src/group/membership/components/GroupMembers.js
- src/group/membership/components/GroupMembers.test.js
- src/sharedData/visualization/components/VisualizationConfigForm/index.js
- Send membership status when updating user role
- Avoid change membership card membership while user is requesting for access
- https://github.com/techmatters/terraso-product/issues/515
> fix: closed group membership fixes

- package-lock.json
- package.json
- Updated shared version
- https://github.com/techmatters/terraso-web-client/issues/1322
> chore: Updated shared version

- src/group/components/GroupView.js
- Reload group data after logout
- https://github.com/techmatters/terraso-web-client/issues/1409
> fix: Reload group data after logout

- package-lock.json
- package.json
Update eslint-config-prettier@9.1.0 eslint-plugin-prettier@5.1.3 stylelint@16.2.1.
> build: update eslint-config-prettier eslint-plugin-prettier stylelint

- package-lock.json
- package.json
> build: update web-vitals@3.5.2

- package-lock.json
- package.json
update react-router-dom@6.22.2.
> build: update react-router-dom@6.22.2

- package-lock.json
- package.json
> build: update use-debounce@10.0.0

- package-lock.json
- package.json
> build: update get-video-id@4.1.5

- package-lock.json
- package.json
> build: update slate-react@0.102.0

- package-lock.json
- package.json
update @typescript-eslint/parser@7.1.0
> build: update @typescript-eslint/parser@7.1.0

- package-lock.json
- package.json
update @mui/icons-material@5.15.11
> build: update @mui/icons-material@5.15.11

- package-lock.json
- package.json
update @mapbox/mapbox-gl-geocoder@5.0.2.
> build: update @mapbox/mapbox-gl-geocoder@5.0.2

- src/account/accountProfileUtils.js
- src/account/components/AccountLogin.js
- src/account/components/AccountProfile.js
- src/account/components/AccountProfile.test.js
- src/account/components/OptionalAuth.js
- src/account/components/OptionalAuth.test.js
- src/account/components/OptionalAuthBottomMessage.js
- src/account/components/OptionalAuthTopMessage.js
- src/account/components/RequireAuth.js
- src/account/components/RequireAuth.test.js
- src/forms/components/Form.js
- src/layout/AppBar.js
- src/layout/AppBar.test.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
- src/navigation/components/Routes.js
- src/navigation/navigationUtils.js
- Redirect user to complete profile after first login
- Stored a new value in local storage to know if the user has already viewed the profile page after the first login
- https://github.com/techmatters/terraso-backend/pull/1195
- https://github.com/techmatters/terraso-web-client/issues/1145
> fix: Redirect user to complete profile after first login

- package-lock.json
- package.json
- src/collaboration/collaborationContext.js
- src/collaboration/components/MembersPage.js
- src/collaboration/components/MembershipCard.js
- src/collaboration/components/MembershipCount.js
- src/collaboration/components/MembershipJoinLeaveButton.js
- src/group/components/GroupForm.js
- src/group/components/GroupList.js
- src/group/components/GroupView.js
- src/group/components/GroupsHomeCard.js
- src/group/groupService.test.ts
- src/group/groupService.ts
- src/group/groupSlice.ts
- src/group/groupUtils.js
- src/landscape/components/LandscapeList.js
- src/landscape/components/LandscapeList.test.js
- src/landscape/components/LandscapeView.js
- src/landscape/landscapeService.test.ts
- src/landscape/landscapeSlice.js
- src/landscape/landscapeUtils.js
- src/permissions/rules.js
- src/storyMap/components/StoryMapsCard.js
- src/storyMap/storyMapUtils.js
Rename MembershipsInfo to MembershipInfo, membershipsSample to memberships.
Fixes https://github.com/techmatters/terraso-client-shared/issues/216
Depends on https://github.com/techmatters/terraso-client-shared/issues/216
> fix: rename MembershipsInfo to MembershipInfo, membershipsSample to memberships

- package-lock.json
- package.json
> build: update mapbox-gl to 3.3.0

- package-lock.json
- package.json
> build: update stylelint@16.3.1

- package-lock.json
- package.json
Update @typescript-eslint/parser@7.6.0.
> build: update @typescript-eslint/parser@7.6.0

- package-lock.json
- package.json
Update react-error-boundary@4.0.13.
> build: update react-error-boundary@4.0.13

- package-lock.json
- package.json
update @testing-library/react to 15.0.0.
> build: update @testing-library/react to 15.0.0

- package-lock.json
- package.json
- src/collaboration/components/MembershipsList.js
- src/common/components/TableResponsive.js
- src/group/components/GroupList.test.js
- src/group/membership/components/GroupMembers.test.js
- src/landscape/components/LandscapeList.js
- src/landscape/components/LandscapeList.test.js
- src/landscape/membership/components/LandscapeMembers.test.js
Update @mui/x-data-grid to 7.1.1.
> build: update @mui/x-data-grid to 7.1.1

- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
Update streets label; remove unused labels.
> fix: update streets label; remove unused labels

- package-lock.json
- package.json
> build: update web-vitals to 4.0.1

- package-lock.json
- package.json
> build: update stylelint to 16.6.1

- package-lock.json
- package.json
update use-debounce to 10.0.1.
> build: update use-debounce to 10.0.1

- package-lock.json
- package.json
update slate-react to 0.105.0.
> build: update slate-react to 0.105.0

- package-lock.json
- package.json
update react-router-dom to 6.23.1.
> build: update react-router-dom to 6.23.1

- package-lock.json
- package.json
> build: update prettier to 3.3.0

- package-lock.json
- package.json
update @mui/x-data-grid to 7.6.1.
> build: update @mui/x-data-grid to 7.6.1

- package-lock.json
- package.json
update react-i18next to 14.1.2.
> build: update react-i18next to 14.1.2

- package-lock.json
- package.json
update i18next-conv to 15.0.0.
> build: update i18next-conv to 15.0.0

- package-lock.json
- package.json
> build: update mapbox-gl to 3.4.0

- package-lock.json
- package.json
update @typescript-eslint/parser to 7.12.0.
> build: update @typescript-eslint/parser to 7.12.0

- package-lock.json
- package.json
update @graphql-codegen/client-preset to 4.2.6.
> build: update @graphql-codegen/client-preset to 4.2.6

- package-lock.json
- package.json
update react-hook-form to 7.51.5.
> build: update react-hook-form to 7.51.5

- package-lock.json
- package.json
update @hookform/resolvers to 3.4.2.
> build: update @hookform/resolvers to 3.4.2

- package-lock.json
- package.json
update @testing-library/jest-dom to 6.4.5.
> build: update @testing-library/jest-dom to 6.4.5

- package-lock.json
- package.json
update testing-library/react to 16.0.0.
> build: update testing-library/react to 16.0.0

- package-lock.json
- package.json
update stylelint@16.7.0 stylelint-prettier@5.0.2
> build: update stylelint@16.7.0 stylelint-prettier@5.0.2

- package-lock.json
- package.json
> build: update prettier to 3.3.3

- package-lock.json
- package.json
> build: update mapbox-gl to 3.5.2

- package-lock.json
- package.json
> build: update web-vitals to 4.2.2

- package-lock.json
- package.json
update slate-react to 0.107.1.
> build: update slate-react to 0.107.1

- package-lock.json
- package.json
> build: update i18next to 23.12.2

- package-lock.json
- package.json
> build: update filesize to 10.1.4

- package-lock.json
- package.json
Update @graphql-codegen/client-preset to 4.3.2
> build: update @graphql-codegen/client-preset to 4.3.2

- package-lock.json
- package.json
update @mui/material to 5.16.4
> build: update @mui/material to 5.16.4

- package-lock.json
- package.json
> build: update get-video-id to 4.1.7

- package-lock.json
- package.json
update @hookform/resolvers to 3.9.0.
> build: update @hookform/resolvers to 3.9.0

- package-lock.json
- package.json
update @ianvs/prettier-plugin-sort-imports to 4.3.1.
> build: update @ianvs/prettier-plugin-sort-imports to 4.3.1

- package-lock.json
- package.json
update @mui/x-data-grid to 7.11.0.
> build: update @mui/x-data-grid to 7.11.0

- package-lock.json
- package.json
update react-router-dom to 6.25.1.
> build: update react-router-dom to 6.25.1

- package-lock.json
- package.json
update react-hook-form to 7.52.1.
> build: update react-hook-form to 7.52.1

- src/common/components/RichTextEditor/utils.js
- src/common/components/RichTextEditor/utils.test.js
- src/landscape/components/LandscapeProfile/ProfileCard.js
use import instead of require for deserialize.
> fix: use import instead of require for deserialize

- package-lock.json
- package.json
- src/group/components/GroupSharedDataVisualization.js
- src/group/components/GroupSharedDataVisualizationConfig.js
- src/landscape/components/LandscapeSharedDataVisualization.js
- src/landscape/components/LandscapeSharedDataVisualization.test.js
- src/landscape/components/LandscapeSharedDataVisualizationConfig.js
- src/navigation/components/Routes.js
- src/sharedData/components/SharedDataEntryFile.js
- src/sharedData/sharedDataFragments.ts
- src/sharedData/sharedDataService.js
- src/sharedData/visualization/components/VisualizationConfigForm/PreviewStep.js
- src/sharedData/visualization/components/VisualizationConfigForm/index.js
- src/sharedData/visualization/components/VisualizationWrapper.js
Added readable ID to support duplicated map titles
- https://github.com/techmatters/terraso-product/issues/555
- https://github.com/techmatters/terraso-backend/pull/1416
- https://github.com/techmatters/terraso-client-shared/pull/821
> feat: Unique urls maps

- package-lock.json
- package.json
update use-debounce to 10.0.3.
> build: update use-debounce to 10.0.3

- package-lock.json
- package.json
update @sentry/react to 8.26.0.
> build: update @sentry/react to 8.26.0

- package-lock.json
- package.json
update @mui/x-data-grid to 7.14.0.
> build: update @mui/x-data-grid to 7.14.0

- package-lock.json
- package.json
update @typescript-eslint/parser to 8.3.0.
> build: update @typescript-eslint/parser to 8.3.0

- package-lock.json
- package.json
update @testing-library/jest-dom to 6.5.0.
> build: update @testing-library/jest-dom to 6.5.0

- package-lock.json
- package.json
update @types/react to 18.3.4.
> build: update @types/react to 18.3.4

- package-lock.json
- package.json
> build: update stylelint to 16.8.2

- package-lock.json
- package.json
> build: update mapbox-gl to 3.6.0

- package-lock.json
- package.json
update react-router-dom to 6.26.1.
> build: update react-router-dom to 6.26.1

- package-lock.json
- package.json
update react-hook-form to 7.53.0.
> build: update react-hook-form to 7.53.0

- package-lock.json
- package.json
> build: update stylelint to 16.9.0

- package-lock.json
- package.json
update react-router-dom to 6.26.2.
> build: update react-router-dom to 6.26.2

- package-lock.json
- package.json
> build: update i18next to 23.15.1

- package-lock.json
- package.json
update @types/react to 18.3.5.
> build: update @types/react to 18.3.5

- package-lock.json
- package.json
update @testing-library/react to 16.0.1.
> build: update @testing-library/react to 16.0.1

- package-lock.json
- package.json
update @types/react to 18.3.7.
> build: update @types/react to 18.3.7

- package-lock.json
- package.json
update @typescript-eslint/parser to 8.6.0.
> build: update @typescript-eslint/parser to 8.6.0

- package-lock.json
- package.json
update @typescript-eslint/parser to 8.7.0.
> build: update @typescript-eslint/parser to 8.7.0

- package-lock.json
- package.json
update @types/lodash to 4.17.9.
> build: update @types/lodash to 4.17.9

- package-lock.json
- package.json
> build: update mapbox-gl to 3.7.0

- package-lock.json
- package.json
update @types/react to 18.3.10.
> build: update @types/react to 18.3.10

- src/storyMap/components/StoryMap.css
Change color of story map chapter links to improve contrast
Fixes #2455.
> fix: change color of story map chapter links to improve contrast

- package-lock.json
- package.json
> build: update uuid to 11.0.3

- package-lock.json
- package.json
> build: update @mui/material@6.1.6

- package-lock.json
- package.json
> build: update web-vitals to 4.2.4

- package-lock.json
- package.json
update use-debounce to 10.0.4.
> build: update use-debounce to 10.0.4

- package-lock.json
- package.json
> build: update i18next@23.16.5

- package-lock.json
- package.json
update @graphql-codegen/client-preset@4.5.0.
> build: update @graphql-codegen/client-preset@4.5.0

- package-lock.json
- package.json
update @testing-library/jest-dom@6.6.3.
> build: update @testing-library/jest-dom@6.6.3

- package-lock.json
- package.json
update @hookform/resolvers to 3.9.1.
> build: update @hookform/resolvers to 3.9.1

- package-lock.json
- package.json
update @ianvs/prettier-plugin-sort-imports to 4.4.0.
> build: update @ianvs/prettier-plugin-sort-imports to 4.4.0

- package-lock.json
- package.json
update @parcel/watcher to 2.5.0.
> build: update @parcel/watcher to 2.5.0

- package-lock.json
- package.json
> build: bump stylelint to 16.11.0

- package-lock.json
- package.json
> build: bump i18next to 24.0.2

- package-lock.json
- package.json
> bump: bump react-i18next to 15.1.3

- package-lock.json
- package.json
> build: bump mapbox-gl to 3.8.0

- package-lock.json
- package.json
bump @typescript-eslint/parser to 8.16.0.
> build: bump @typescript-eslint/parser to 8.16.0

- package-lock.json
- package.json
- src/index.css
> build: bump prettier to 3.4.1

- package-lock.json
- package.json
> build: bump @mui/material to 6.1.9

- package-lock.json
- package.json
bump @graphql-codegen/client-preset to 4.5.1
> build: bump @graphql-codegen/client-preset to 4.5.1

- package-lock.json
- package.json
> build: bump yup to 1.6.1

- package-lock.json
- package.json
> build: bump stylelint to 16.12.0

- package-lock.json
- package.json
> build: update prettier to 3.4.2

- package-lock.json
- package.json
update @mapbox/mapbox-gl-draw@1.5.0 mapbox-gl@3.9.1.
> build: update @mapbox/mapbox-gl-draw@1.5.0 mapbox-gl@3.9.1

- package-lock.json
- package.json
> build: update @mui/material@6.3.0

- package-lock.json
- package.json
> build: update react-router to 7.1.1

- package-lock.json
- package.json
update slate-react to 0.112.0.
> build: update slate-react to 0.112.0

- package-lock.json
- package.json
bump react-hook-form to 7.54.2.
> build: bump react-hook-form to 7.54.2

- package-lock.json
- package.json
> build: update jest-when to 3.7.0

- package-lock.json
- package.json
update react-i18next to 15.4.0.
> build: update react-i18next to 15.4.0

- package-lock.json
- package.json
bump @testing-library/react@16.1.0.
> build: bump @testing-library/react@16.1.0

- package-lock.json
- package.json
update react-error-boundary to 5.0.0.
> build: update react-error-boundary to 5.0.0

- package-lock.json
- package.json
> build: bump mapbox-gl to 3.9.3

- package-lock.json
- package.json
build: bump stylelint to 16.13.2
> build: bump stylelint to 16.13.2

- package-lock.json
- package.json
build: bump stylelint to 16.13.2
> build: bump react-highlight-words to 0.21.0

- package-lock.json
- package.json
update eslint-plugin-prettier to 5.2.2.
> build: update eslint-plugin-prettier to 5.2.2

- package-lock.json
- package.json
update @typescript-eslint/parser to 8.20.0.
> build: update @typescript-eslint/parser to 8.20.0

- package-lock.json
- package.json
update eslint-config-prettier@10.0.1.
> build: update eslint-config-prettier@10.0.1

- package-lock.json
- package.json
> build: update @types/lodash@4.17.14

- package-lock.json
- package.json
> build: update @sentry/react@8.50.0

- package-lock.json
- package.json
update @ianvs/prettier-plugin-sort-imports@4.4.1.
> build: update @ianvs/prettier-plugin-sort-imports@4.4.1

- package-lock.json
- package.json
> build: update uuid@11.0.5

- src/account/components/AccountLogin.js
- src/localization/locales/en-US.json
- src/localization/locales/es-ES.json
update tos/privacy on welcome screen to match google's order.
> fix: update tos/privacy on welcome screen to match google's order

- package-lock.json
- package.json
update stylelint@16.13.2 stylelint-prettier@5.0.3.
> build: update stylelint@16.13.2 stylelint-prettier@5.0.3

- package-lock.json
- package.json
> build: update uuid@11.1.0

- package-lock.json
- package.json
> build: update lint-staged to 15.5.0

- package-lock.json
- package.json
> build: update stylelint to 16.16.0

- package-lock.json
- package.json
> build: update mapbox-gl to 3.10.0

- package-lock.json
- package.json
> build: update notistack to 3.0.2

- package-lock.json
- package.json
update react-i18next to 15.4.1
> build: update react-i18next to 15.4.1

- package-lock.json
- package.json
> build: update react-router to 7.4.0

- package-lock.json
- package.json
update npmupdate to @parcel/watcher
> build: update @parcel/watcher to 2.5.1

- package-lock.json
- package.json
update npmupdate to slate-react
> build: update slate-react to 0.112.1

- package-lock.json
- package.json
update npmupdate to @types/lodash
> build: update @types/lodash to 4.17.16

- package-lock.json
- package.json
update npmupdate to @testing-library/react
> build: update @testing-library/react to 16.2.0

- package-lock.json
- package.json
update @graphql-codegen/cli@5.0.5 @graphql-codegen/client-preset@4.7.0
> build: update @graphql-codegen/cli@5.0.5 @graphql-codegen/client-preset@4.7.0

- package-lock.json
- package.json
update npmupdate to @hookform/resolvers
> build: update @hookform/resolvers to 4.1.3

- package-lock.json
- package.json
update @hello-pangea/dnd to 18.0.1.
> build: update @hello-pangea/dnd to 18.0.1

- package-lock.json
- package.json
update npmupdate to @sentry/react
> build: update @sentry/react to 9.9.0

- package-lock.json
- package.json
update npmupdate to eslint-plugin-prettier
> build: update eslint-plugin-prettier to 5.2.5

- package-lock.json
- package.json
> build: update web-vitals to 5.0.0

- package-lock.json
- package.json
update eslint-config-prettier to 10.1.3
> build: update eslint-config-prettier to 10.1.3

- package-lock.json
- package.json
> build: update lint-staged to 15.5.2

- package-lock.json
- package.json
update eslint-plugin-prettier to 5.4.0
> build: update eslint-plugin-prettier to 5.4.0

- package-lock.json
- package.json
> build: update mapbox-gl to 3.11.1

- package-lock.json
- package.json
update @testing-library/react to 16.3.0
> build: update @testing-library/react to 16.3.0

- package-lock.json
- package.json
update @graphql-codegen/cli@5.0.6 @graphql-codegen/client-preset@4.8.1
> build: update @graphql-codegen/cli@5.0.6 @graphql-codegen/client-preset@4.8.1

- package-lock.json
- package.json
update @typescript-eslint/parser to 8.32.0
> build: update @typescript-eslint/parser to 8.32.0

- package-lock.json
- package.json
> build: update react-router to 7.5.3

- package-lock.json
- package.json
update slate-history to 0.113.1
> build: update slate-history to 0.113.1

- package-lock.json
- package.json
update @sentry/react to 9.23.0
> build: update @sentry/react to 9.23.0

- package-lock.json
- package.json
update eslint-config-prettier to 10.1.5
> build: update eslint-config-prettier to 10.1.5

- package-lock.json
- package.json
> build: update web-vitals to 5.0.1

- package-lock.json
- package.json
> build: update mapbox-gl to 3.12.0

- package-lock.json
- package.json
update @types/lodash to 4.17.17
> build: update @types/lodash to 4.17.17

- package-lock.json
- package.json
> build: update lint-staged to 16.1.0

- package-lock.json
- package.json
- src/account/components/AccountProfile.js
- src/common/components/TableResponsive.js
- src/forms/components/Form.js
- src/group/components/GroupList.test.js
- src/group/components/GroupView.js
- src/home/components/Home.js
- src/landscape/components/LandscapeProfile/ProfileCard.js
- src/landscape/components/LandscapeProfile/index.js
- src/landscape/components/LandscapeView.js
- src/layout/Footer.js
- src/sharedData/components/SharedDataEntryBase.js
- src/sharedData/components/SharedDataEntryFile.js
- src/sharedData/components/SharedDataEntryLink.js
- src/sharedData/visualization/components/VisualizationConfigForm/AnnotateStep.js
- src/sharedData/visualization/components/VisualizationConfigForm/SelectDataFileStep.js
- src/sharedData/visualization/components/VisualizationConfigForm/SetDatasetStep.js
- src/sharedData/visualization/components/VisualizationConfigForm/VisualizeStep.js
- src/storyMap/components/StoryMapForm/ChapterForm.js
- src/storyMap/components/StoryMapForm/ChaptersSideBar.js
- src/storyMap/components/StoryMapForm/TopBar.js
- src/storyMap/components/StoryMapForm/TopBarContainer.js
- src/storyMap/components/StoryMapForm/TopBarPreview.js
- src/storyMap/components/StoryMapForm/index.js
- src/storyMap/components/StoryMapsCard.js
- src/storyMap/components/StoryMapsToolHome.js
update @mui/x-data-grid to 8.4.0
> build: update @mui/x-data-grid to 8.4.0

- src/sharedData/components/SharedDataEntryBase.js
- src/sharedData/components/SharedDataEntryFile.js
- src/sharedData/visualization/components/VisualizationConfigForm/SelectDataFileStep.js
- src/storyMap/components/StoryMapsCard.js
Missed fized for Grid V2 support
> fix: Fixes Grid V2

- src/storyMap/components/StoryMapForm/ChaptersSideBar.js
> fix: can't change chapter while text field is focused

- src/App.js
- src/navigation/components/Routes.js
- src/storyMap/components/StoryMapForm/index.js
> experiment: add `/embed` to the end of a story map edit URL to get a cleaner view

- src/account/components/AccountProfile.js
- src/common/components/TableResponsive.js
- src/forms/components/Form.js
- src/group/components/GroupList.js
- src/landscape/components/LandscapeList.js
- src/sharedData/visualization/components/VisualizationConfigForm/AnnotateStep.js
- src/sharedData/visualization/components/VisualizationConfigForm/SelectDataFileStep.js
- src/storyMap/components/StoryMapForm/ChapterForm.js
- src/storyMap/components/StoryMapForm/ChaptersSideBar.js
- src/storyMap/components/StoryMapsCard.js
- src/storyMap/components/StoryMapsToolHome.js
update MUI Grid for Gridv2 compatibility
See details at https://mui.com/material-ui/migration/upgrade-to-grid-v2/
Fixes https://github.com/techmatters/terraso-web-client/issues/2672
> fix: update MUI Grid for Gridv2 compatibility

- src/account/components/AccountAuthCallback.tsx
- src/account/components/AccountLogin.js
- src/config.ts
- src/navigation/components/Routes.js
- src/navigation/navigationUtils.js
Modifies the login process to work from multiple domains.
Related to techmatters/terraso-backend#1709
> feat: modify login to work from multiple domains

- src/sharedData/components/SharedDataEntryBase.js
- src/sharedData/components/SharedDataEntryFile.js
- src/sharedData/components/SharedDataEntryLink.js
- Refactor for readability
- Removed icon top margin and aligned to the center
- https://github.com/techmatters/terraso-web-client/issues/2731
> fix: shared files alignment

- package-lock.json
- package.json
update @testing-library/jest-dom to 6.8.0
> build: update @testing-library/jest-dom to 6.8.0

- package-lock.json
- package.json
> build: update lint-staged to 16.1.5

- package-lock.json
- package.json
> build: update use-debounce to 10.0.5

- package-lock.json
- package.json
> build: update web-vitals to 5.1.0

- package-lock.json
- package.json
> build: update @sentry/cli to 2.52.0

- package-lock.json
- package.json
update @ianvs/prettier-plugin-sort-imports to 4.6.2
> build: update @ianvs/prettier-plugin-sort-imports to 4.6.2

- package-lock.json
- package.json
update react-hook-form to 7.62.0
> build: update react-hook-form to 7.62.0

- package-lock.json
- package.json
> build: update @types/jest to 30.0.0

- package-lock.json
- package.json
update react-i18next to 15.7.1
> build: update react-i18next to 15.7.1
