src/dashboard/components/Dashboard.test.js, src/landscape/components/LandscapesDashboardDiscoveryCard.js
Remove Landascapes discovery card if there are no landascapes
Fixes #119 
Screenshot:
=> fix: Remove discovery card if no landscapes

package.json, src/group/components/GroupForm.js, src/group/components/GroupForm.test.js
This change updates the URL field validation on `GroupForm` to allow users
inform URLs without the protocol (HTTPS). To make it work, it was added
a transform function to add the protocol value if needed before calling
the field validation and sending the data to the API.
This fix:
- #115
=> fix: GroupForm URL field validation

src/config.js
Use `127.0.0.1` instead of `localhost` for default URL. Allows Google authentication in local development environment.
=> fix: use 127.0.0.1 instead of localhost for default URL

src/common/components/Table.js, src/group/components/GroupList.test.js, src/landscape/components/LandscapeList.test.js
Show 15 items per page instead of 10.
Fixes #135.
=> fix: set pagination size to 15

src/tool/components/Tool.js, src/tool/components/ToolList.js
Remove placeholder text and buttons.
Fixes #139, Fixes #141.
=> fix: tools page: remove placeholder text and buttons

locales/po/en-US.po, src/group/components/GroupDefaultHomeCard.js, src/group/components/GroupsHomeCard.js, src/home/components/Home.js, src/home/components/Home.test.js, src/home/components/HomeCard.js, src/home/homeService.js, src/home/homeSlice.js, src/landscape/components/LandscapeDefaultHomeCard.js, src/landscape/components/LandscapesHomeCard.js, src/landscape/components/LandscapesHomeDiscoveryCard.js, src/localization/locales/en-US.json, src/navigation/Routes.js, src/state/store.js, src/tool/components/ToolHomeCard.js
This change is necessary to reflect the business decision to refer to
the home page as Home instead of Dashboard since the structure of the
home isn't a Dashboard.
It fixes:
- #31
=> chore: rename Dashboard references to Home

src/navigation/Navigation.js
Add a hover color to top navbar.
Fixes #134.
=> fix: add hover to navbar

src/account/components/AccountProfile.js, src/forms/components/FormField.js
Show the email address as plain text, not a disabled form field. Fields should not be disabled unless there is some way of enabling them. 
Fixes #127.
Go to http://127.0.0.1:3000/account/profile
=> fix: show email address as plain text, not form field

src/localization/components/LocalePicker.js
Only show language picker if at least two languages are present.
Fixes #130.
=> feat: only show language picker if multiple languages are present

src/tool/components/Tool.js
- Tools page content changed, now it is not using list content
Fixes #187 
Screenshot:
=> fix: Tools page not using list content

src/index.js, src/navigation/Navigation.js
Simplify top-level markup by using `<main>` and promoting `<nav>` so it's no longer inside a container.
=> fix: simplify top-level markup by using <main> and promoting <nav>

src/account/components/AccountLogin.js, src/common/components/AppBar.js, src/common/components/UnexpectedError.js
Correctly set width and height for Terraso logos. The height was set as `35px` instead of `35` and the width was not set.
=> fix: correctly set width and height for logos

package-lock.json, package.json, src/gis/components/Map.js, src/landscape/components/LandscapeView.js, src/landscape/landscapeFragments.js, src/landscape/landscapeService.js, src/landscape/landscapeUtils.js, src/landscape/landscapeUtils.test.js
This change updates the Map component to support it receiving a GeoJSON
objects. This GeoJSON is used to add a new map polygon layer.
The new `geojson` property is already being used to the Landscape's
`areaPolygon` attribute. When a `areaPolygon` is used, the bounding box
of this polygon is used. Otherwise, the Landscape's position bounding
box continue being used.
Even before this change, the `LandscapeView` had a limitation to don't
properly handle the situation where a Landscape has no location. This
limitation isn't addressed in this change.
Fix: #192
=> feat: add Landscape area polygon to the map 

src/gis/components/Map.js
This change fixes the zoom out control. Although the root cause is not
exactly known, the assumption was the `zoomDelta` option being
fractional without changing the `zoomSnap` option. So, the `zoomSnap`
was set to also be fractional. It worked.
=> fix: map zoom out control

README.md
Use .org instead of .com in sample run commands.
=> docs: use .org instead of .com in sample run commands

src/localization/components/LocalePicker.js, src/localization/components/LocalePicker.test.js
- Added check to save language preference if there is a logged in user.
=> fix: Only save preference if user is logged in

src/landscape/components/LandscapeBoundaries.js
Works around Dropzone bug [#1164](https://github.com/react-dropzone/react-dropzone/issues/1164) / [#1141](https://github.com/react-dropzone/react-dropzone/issues/1141)
1. Go to boundary upload page
2. Click on "Select File"
3. Confirm only `.json` and `.geojson` files appear in open dialog
=> fix: don't use on FS API boundary upload

src/localization/locales/en-US.json, src/localization/locales/es-ES.json
The `send us a message` link now loads the contact form. Added missing URL to strings.
Fixes #290.
=> fix: send us a message link now loads contact form

src/common/components/AppBar.js, src/common/components/ConditionalLink.js
Disables the link on the logo when on home page (don't self-link).
Fixes #294.
=> fix: Disable link on logo when on home page

src/notifications/NotificationsWrapper.js
Prevents snackbar from being truncated on right side of mobile device screens.
Fixes #303.
=> fix: reduce width of snackbar alert

src/landscape/components/LandscapeBoundaries.test.js, src/localization/locales/en-US.json, src/localization/locales/es-ES.json
Improve consistency and ease of comprehension when updating boundaries.
=> fix: Use Save Changes for button name

src/monitoring/rollbar.js
Disable rollbar when token is not present.
Fixes #318.
=> fix: disable rollbar when token is not present

src/localization/locales/en-US.json, src/localization/locales/es-ES.json, src/terrasoBackend/api.js
Pass input data to error handler. Use custom message for groups that don't have a unique name.
Fixes #291.
=> fix: Better error messages for duplicate group errors

src/gis/components/Map.css
Increases the size of the drop pin icon by 50%
Fixes #337.
=> fix: increase size of drop pin button icon

src/gis/components/Map.css, src/gis/components/Map.js
Makes search field top left and pin to the right of that.
=> fix: reorder map controls per spec

src/common/components/SocialShare.js, src/common/components/SocialShare.test.js, src/common/components/Stepper.js, src/group/components/GroupView.js, src/landscape/components/LandscapeNew.js, src/landscape/components/LandscapeView.js, src/localization/locales/en-US.json, src/localization/locales/es-ES.json
Adds a share button to group and landscape pages. When clicked, a modal appears, allowing the user to share via email, WhatsApp and Facebook and to copy the link to the clipboard.
Fixes #353.
=> feat: social sharing of groups and landscapes

src/group/components/GroupView.js
Removes duplicate upgrade group button.
Fixes #364.
=> fix: remove duplicate update group button

src/common/components/SocialShare.js
Use the same size headings through social share dialog.
Fixes #365.
=> fix: use same size for both subheadings in social share dialog

src/group/components/GroupView.js, src/group/membership/components/GroupMembershipCard.js, src/landscape/components/LandscapeView.js
Match heights of member and about cards on group and landscape pages.
Fixes #362.
Based on https://stackoverflow.com/questions/55824260/same-height-cards-in-material-ui
=> fix: match heights of member and about cards

src/sharedData/components/SharedDataEntry.js
Improve the contrast of text in the data entry card.
Fixes #393
=> fix: use darker gray for shared data entries

src/localization/locales/en-US.json, src/localization/locales/es-ES.json
Update capitalization and quotation marks for shared files card.
Fixes #387.
=> fix: remove quotes and change capitalization for shared files card

src/localization/locales/en-US.json, src/localization/locales/es-ES.json, src/sharedData/components/SharedDataCard.js
Update the shared files card to use "landscape" or "group" as appropriate (and not just "group").
Fixes #391.
=> fix: use "landscape" or "group" as appropriate on shared data card

src/common/components/EditableText.js, src/sharedData/components/SharedDataEntry.js
In shared files card, hide delete/download buttons when editing file name. Make more room for the text field.
Fixes #390.
=> fix: hide delete/download buttons when editing file name

src/account/components/AccountLogin.js
Add margin to disclaimer text on login screen on mobile.
Fixes #404.
=> fix: add margin to disclaimer text on login screen on mobile

src/common/utils.js, src/landscape/components/LandscapeForm/BoundaryStep.js, src/landscape/components/LandscapeForm/InfoStep.js
When creating a landscape, scroll to the top of the viewport after each step.
Fixes #397.
=> fix: scroll to top between steps when creating landscapes

src/localization/locales/en-US.json, src/localization/locales/es-ES.json
make the list_new_description consistent for groups and landscapes
=> fix: make list_new_description consistent for groups and landscapes

src/layout/Footer.js
On desktop, make the footer same width as the rest of the page
=> fix: make footer same width as the rest of the page

src/group/membership/components/GroupMembershipPendingWarning.js, src/localization/locales/en-US.json
Replaced warning icon with notification bell icon for pending members.
Fixes #443
=> Feat: replaced warning icon with notification bell for pending members

src/account/components/AccountLogin.js, src/layout/PageHeader.js
Ensures Terraso image is part of `<h1>` on login screen.
Fixes #470.
=> fix: Ensures Terraso image is part of `<h1>` on login screen

src/layout/Footer.js, src/localization/locales/en-US.json, src/localization/locales/es-ES.json
* Add an off-screen heading `<h2>` with the text "Footer" as the first child in the <footer> element
* Wrap the footer links in a `<nav>` element with aria-label="Footer" to provide an accessible name for the landmark.
* Apply an aria-label on the `<ul>` with a value of "Footer Navigation".
Fixes #464.
=> fix: Make footer more accessible

src/localization/locales/en-US.json
Fix a grammatical error in group intro text.
=> fix: correct grammar in group intro message

src/account/components/AccountAvatar.js, src/account/components/AccountProfile.js, src/account/components/AccountProfile.test.js, src/common/components/AppBar.js, src/group/membership/components/GroupMembers.test.js, src/index.js, src/landscape/membership/components/LandscapeMembers.test.js, src/layout/PageHeader.js, src/navigation/Navigation.js, src/navigation/SkipLinks.js, src/navigation/SkipLinks.test.js
Improves header accessibility by hiding separator and avatar from screen readers. Improves skip links accessibility.
Fixes #469, Fixed #473.
=> fix: improve site header accessibility

src/landscape/components/LandscapeForm/InfoStep.js, src/landscape/components/LandscapeNewFormDrawPolygon.test.js, src/landscape/components/LandscapeNewFormGeoJson.test.js, src/landscape/components/LandscapeNewFormInfo.test.js, src/landscape/components/LandscapeNewFormPin.test.js, src/landscape/components/LandscapeUpdateProfile.test.js
On the landscape creation form:
- automatically set the width of the popup menu so long country and region names are no longer truncated
- add an ID to the popup menu so aria-labelledby is includes both the label and the country name
Fixes #509. Fixes #511.
=> fix:  on landscape form country menu: set width to auto, add ID

src/sharedData/visualization/components/VisualizationWrapper.js
for visualization_file_load_error, show file name instead of [Object object]
Before:
After:
1. Go to https://app.staging.terraso.net/landscapes/abancay-apurimac/map/landscape-details
2. Observe error message
=> fix: for visualization_file_load_error, show file name instead of [Object object]

src/landscape/components/LandscapeForm/Actions.js, src/landscape/components/LandscapeForm/AffiliationStep.js, src/landscape/components/LandscapeForm/BoundaryStep.js, src/landscape/components/LandscapeForm/DevelopmentStrategyStep.js, src/landscape/components/LandscapeForm/KeyInfoStep.js, src/landscape/components/LandscapeForm/ProfileStep.js
- Keep boundary step seelcted option when going back
- Remove save for now from key info step
=> fix: Keep boundary current option and remove save for now

src/common/components/CharacterCounter.js, src/forms/components/FormField.js, src/landscape/components/LandscapeForm/DevelopmentStrategyStep.js, src/landscape/components/LandscapeForm/KeyInfoStep.js
- Added aouto size textarea for landscape description and development strategy fields
- Added character counter fro landscape description
=> Feat: Profile textarea auto size and counter

.editorconfig, src/localization/locales/en-US.json, src/localization/locales/es-ES.json
My editor keeps on automatically formatting the JSON files to 2 space thanks to the editorconfig, which is inconvenient. This PR should change it to 4 spaces, which matches what the present files have.
=> fix: Set 4-space spacing for JSON files in editorconfig

src/landscape/components/LandscapeProfile/ProfileCard.js
Avoid null dereference in population formatting.
=> fix: Avoid null dereference in population formatting

src/localization/locales/en-US.json, src/localization/locales/es-ES.json
Pluralized "livelihoods" on page title.
Fixes #629.
=> fix: pluralized "livelihoods"

src/sharedData/visualization/components/VisualizationConfigForm/SetDatasetStep.js, src/sharedData/visualization/components/VisualizationConfigForm/SetDatasetStep.test.js
Previously the data visualization in creating a map would not display null columns. This is due to the somewhat weird properties of Javascript arrays.
The problem: `Sheets.utils.sheet_to_json`, when called with '{header:
1}' will leave blank spots in the array. For example: `1,,3` becomes
`Array(3)[1, <1 empty slot>, 3]`. This is a Javascript array
quirk. However the previous code iterated over an array, to these
blank columns were just "skipped".
This PR changes `Sheets.utils.sheet_to_json` to use `{header:
headers}`. Because the headers are parsed from the sheet itself, this
should preserve the order of the headers as well.
Fixes #574
In contrast to the bug report, you can see that the null rows are now displayed as blank columns.
=> fix: Display null columns in Mapping data preview

src/landscape/components/LandscapeForm/DevelopmentStrategyStep.js, src/landscape/components/LandscapeForm/ProfileStep.js, src/localization/locales/en-US.json, src/localization/locales/es-ES.json
Add paragraph breaks before "learn more" in help text.
Fixes #650.
=> fix: add paragraph breaks before "learn more" in help text

src/landscape/components/LandscapeForm/ProfileUpdate.test.js
Removes quotes around `ECOSYSTEM_TYPE ` constant.
=> style: linter JS formatting cleanup

src/group/components/GroupList.js, src/group/components/GroupList.test.js
* tail-truncate website and email with ellipses
* widen group name column and shrink other columns
* don't display `https://` on websites
Fixes #654.
=> fix: improve group list view formatting

.github/workflows/build.yml, .github/workflows/check-commits.yml, .github/workflows/localization.yml
- Uses Node 16
- Avoids deprecation warnings
=> chore: update GitHub actions versions

src/gis/components/Map.css
sets the default text wrapping behavior for leaflet map popup widgets to "overflow-wrap: anywhere;" (see https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Text/Wrapping_Text for details). this makes sure for now that text will never extend beyond the contents' box
i found this bug also existed on e.g. the landscapes view if a landscape name contained a very long word, and is fixed there as well
i'm not sure how to test for this
we would maybe like to do something more subtle eventually but i will let someone with a more designer brain put thought into that rather than overworking my store-brand brain
Fixes #554 
create a landscape with a name that contains a long word and select it in the map on the landscapes page, or create a data viz map that displays a string column which contains …
=> fix: set a default overflow-wrap for popup content in leaflet map widgets

src/landscape/components/LandscapeView.js, src/landscape/components/LandscapeView.test.js
Hides the "Something wrong with the map? ... contact manager" message on the landscape page from irrelevant users (i.e. managers).
I need help writing the tests for this, & for someone to confirm the way I determined if the user is a manager is idiomatic.
Fixes #453 
View a landscape that you are a manager of & confirm the msg is not there, view a landscape that you are not a manager of and confirm the msg is there.
=> fix: hide "contact manager" msg for managers

src/landscape/components/LandscapeView.js, src/landscape/components/LandscapeView.test.js, src/permissions/components/Restricted.js, src/permissions/components/Restricted.test.js
The Restricted component previously could only restrict a component to users with a permission, now it has an argument toggle whether it restricts to users with or without a permission. The new argument is used to clean up some code duplication i introduced in LandscapeView
should be no visible changes, just a transparent refactor
=> refactor: allow Restricted component to hide children when users do not have a permission

src/common/components/AppBar.js, src/common/components/AppBar.test.js, src/localization/locales/en-US.json, src/localization/locales/es-ES.json
changes alt text of title bar logo from "Terraso" to "Logo: Terraso"
not actually trying to merge this, not sure what the exact workflow is for updating text + i18n yet, just going thru the motions of a PR
Fixes #526 
alt text of title bar logo should now read "Logo: Terraso" instead of "Terraso"
=> fix: update title bar logo alt text

src/storyMap/components/StoryMap.js
The story map flow provides a way to change the layers being displayed on each chapter, through the `onChapterEnter` and `onChapterExit` properties of the chapter or the title transition. Right now the `onChapterEnter` is not always executing because there is a condition for the location change on the map that will return early if there is no need for a location change, but there is a situation where there can be layer changes without a location change.
This fix is removing the early return so that the rest of the functionality can still be executed.
Fixes #....
=> fix: Layers not always changing on story map transition

src/common/components/SocialShare.js
Fix layout of social share dialog:
- render properly on mobile
- don't wrap button when its label changes after click
Fixes #442.
=> fix: improve social share dialog layout

src/localization/locales/en-US.json, src/localization/locales/es-ES.json, src/storyMap/components/StoryMapForm.test.js, src/storyMap/components/StoryMapNew.js, src/storyMap/components/StoryMapUpdate.js, src/storyMap/components/StoryMapsToolHome.js, src/storyMap/components/UserStoryMap.js
Add page titles for story map new/edit/home pages.
Fixes #801.
1. https://app.terraso.org/tools/story-maps
2. https://app.terraso.org/tools/story-maps/new
3. Create a story map, enter a title, click "Save draft"
=> fix: add page titles for story map new/edit/home pages

src/account/components/AccountLogin.js, src/account/components/AccountProfile.js, src/common/components/ExternalLink.js, src/group/components/GroupForm.js, src/group/membership/components/GroupMembershipJoinLeaveButton.js, src/landscape/components/LandscapeForm/BoundaryStepUpdate.js, src/landscape/components/LandscapeForm/New.js, src/sharedData/components/SharedDataEntryBase.js, src/sharedData/components/SharedDataEntryLink.js, src/sharedData/components/SharedDataUpload/index.js, src/sharedData/sharedDataHooks.js, src/sharedData/visualization/components/VisualizationConfigForm/PreviewStep.js, src/storyMap/components/StoryMapNew.js, src/storyMap/components/StoryMapUpdate.js
Plausible
- tag tracking for shared links by group/landscape
- track logins by SSO type
Fixes #803, #484.
=> fix: tag shared links by group/landscape and track logins

src/common/components/EditableText.js, src/group/components/GroupSharedDataUpload.js, src/group/components/GroupSharedDataUploadFiles.test.js, src/group/groupService.js, src/group/membership/components/GroupMembers.js, src/group/membership/components/GroupMembers.test.js, src/group/membership/components/GroupMembershipCard.test.js, src/group/membership/components/groupMembershipConstants.js, src/landscape/components/LandscapeSharedDataUpload.js, src/landscape/components/LandscapeSharedDataUploadLinks.test.js, src/landscape/components/LandscapeView.test.js, src/permissions/components/Restricted.js, src/permissions/index.js, src/permissions/rules.js, src/sharedData/components/SharedDataEntryBase.js, src/tests/constants.js
Improve permission checks for file uploads and group member lists
Ensure users are redirected when the attempt to access `/members` or `/upload`
Fixes #811
Backend: https://github.com/techmatters/terraso-backend/pull/419
Need to update query after https://github.com/techmatters/terraso-web-client/pull/857 is merged.
=> fix: improve permission checks for file uploads and group member lists

src/localization/locales/en-US.json, src/localization/locales/es-ES.json
Update email notification strings on account profile page.
Fixes #839.
=> fix: update email notification strings

src/common/components/Table.js
* add `pageSizeOptions` to data grid to silence warning
```
console.warn
MUI: The page size `15` is not preset in the `pageSizeOptions`
Add it to show the pagination select.
```
* remove unused `rowsPerPageOptions`
=> fix: add pageSizeOptions to data grid to silence warning

src/common/components/RichTextEditor/index.js, src/common/components/RichTextEditor/index.test.js, src/localization/locales/en-US.json, src/localization/locales/es-ES.json
Clear url when link dialog opens in richtext editor
Fixes #800
=> fix: Clear url when link dialog opens in richtext editor

src/landscape/components/LandscapeForm/ProfileImageStep.js
Correct typo in `form_profile_image_description_helper_text` key.
Fixes #887.
=> fix: correct typo in form_profile_image_description_helper_text key

src/landscape/components/LandscapeListMap.css
Update the cluster map to use the new 1000L orange (`#ff580d`).
Fixes #644.
=> fix: update cluster map color (new 1000L orange)

src/landscape/components/LandscapeListMap.css
Restore alpha/transparency to outer ring on map.
=> fix: add alpha/transparency to outer ring on map

scripts/docker/run.sh
Forgot to remove a reference to jsconfig when migrating to Typescript!
=> fix: mount tsconfig instead of jsconfig in Docker

src/account/components/AccountProfile.js, src/localization/locales/en-US.json, src/localization/locales/es-ES.json
Inconsistent text when validating account profile changes
1. Go to URL: https://app.terraso.org/account/profile
2. Clear the given name field
3. Press save profile
4. Observe text
=> fix: inconsistent text validating account profile changes

src/layout/AppBar.js, src/storyMap/components/StoryMapsHomeCardDefault.js, src/tool/components/ToolHomeCard.js
Rework tool and storymap cards on home page to match.
Make app bar divider gray.
=> fix: rework tool and storymap cards on home page; color divider in app bar

src/common/components/RichTextEditor/index.js
- Curried insert link function to keep selection before focus changes
Fixes #884
=> fix: Curried insert link function to keep selection before focus changes

src/storyMap/components/StoryMapsHomeCardDefault.js
Correct link to story maps (on story maps home card).
Fixes #953.
=> fix: correct link to story maps

src/landscape/components/LandscapeListMap.js, src/landscape/components/LandscapeProfile/AffiliationCard.js, src/landscape/components/LandscapeProfile/DevelopmentStrategyCard.js, src/landscape/components/LandscapeProfile/KeyInfoCard.js, src/landscape/components/LandscapeProfile/ProfileCard.js, src/landscape/components/LandscapesHomeCard.js, src/layout/Footer.js, src/navigation/components/Breadcrumbs.js, src/sharedData/components/SharedDataEntryFile.js
Replace this old code:
```
import { Link as RouterLink } from 'react-router-dom';
```
With this new code:
```
import RouterLink from 'common/components/RouterLink';
```
Fixes #930
=> Fix: clean up routerlink code

src/forms/yup.js, src/landscape/components/LandscapeForm/KeyInfoStep.js, src/localization/locales/en-US.json, src/localization/locales/es-ES.json
yup.setLocale section is modified to include a condition based on the path parameter in the required method
Fixes #638 
1. Go to URL: https://app.staging.terraso.net/landscapes/[landscape slug]/edit
2. Clear value in country select
3. Watch error message
=> Fix: customize message for blank select values

package.json
The graphql codegen was not including nested fragments in the generated GraphQL documents. This adds a config option to ensure that fragments are included properly. See https://github.com/dotansimha/graphql-code-generator/issues/4684 for context.
Previously broken GraphQL queries should now work (e.g. on logging in).
=> fix: properly generate nested graphql fragments

src/group/membership/components/GroupMembersList.js, src/group/membership/components/GroupMembershipJoinLeaveButton.js, src/home/homeService.js, src/landscape/landscapeFragments.js, src/landscape/landscapeService.js, src/sharedData/sharedDataFragments.js, src/sharedData/sharedDataService.js, src/storyMap/storyMapFragments.js, src/storyMap/storyMapService.js, src/taxonomies/taxonomiesFragments.js, src/taxonomies/taxonomiesService.js, src/terrasoApi/group/groupFragments.ts, src/terrasoApi/group/groupService.ts, src/terrasoApi/group/groupSlice.ts, src/terrasoApi/group/groupUtils.ts
We are getting GraphQL errors in the frontend because the mixed format of partially hand-written, partially generated GraphQL operations didn't work properly when inlining nested fragments between the two modes. This PR migrates the remaining GraphQL queries to codegen.
Since we didn't have any tests that caught this, we will need to manually verify the fix works. I'm not sure what would be a good stopgap way to test for this until integration tests are set up (which would definitely have caught this).
Navigate to landscape page, there should be no error.
=> fix: more GraphQL migration bugs

src/forms/yup.js, src/group/components/GroupForm.js
add a notRequired() check for group website form and allow empty input for custom url validation
1. Go to URL: http://127.0.0.1:3000/groups/new
2. Fill out Name and Description but not website
3. Groups should be successful
=> fix: allow empty checks for custom url validation

src/landscape/landscapeService.test.ts, src/terrasoApi/group/groupUtils.ts
Previous changes assumed that the groups passed into groupUtils would always be non-null. This is currently not the case, so this change undoes that assumption.
Should load landscapes page ok in environments where landscapes have no default group in DB.
=> fix: revert assumption that landscape default groups are non-null in client

src/landscape/components/LandscapeView.js
The Update Map button had underline on focus because it was also a RouterLink. I removed the RouterLink component and added an onClick handler (which matches other buttons in the app).
=> fix: use RouterButton instead of RouterLink for Update Maps button

src/localization/locales/en-US.json, src/localization/locales/es-ES.json, src/storyMap/components/StoryMapForm/EditableMedia.js
Change editable embedded title and button text from "Delete audio" to "Remove video"
Fixes https://github.com/techmatters/terraso-web-client/issues/993
1. Create a story map
2. add a chapter
3. associate chapter with a youtube video, EG: https://youtu.be/cNQQUWDVtfo
4. Delete media for video
5. See the error
=> fix: update editable embedded text

src/group/membership/components/GroupMemberLeave.js, src/landscape/components/LandscapeList.test.js, src/localization/locales/en-US.json
Just a bit of tidying in the code. I can't actually find the word "Connect" anywhere on the site so it might be unused? But would require digging into the group UI code a bit more so just submitting this quick PR because it is faster than opening an issue.
=> fix: minor text label typo/inconsistencies

src/landscape/components/LandscapeSharedDataVisualizationConfig.test.js
Increases timeout on the "Create visualization" test of "LandscapeSharedDataVisualizationConfig"
Fixes #992 
Hard to verify for sure because it's an intermittent test flake, but I will re-run the test action in CI several times and hope it succeeds consistently :shrug:
=> fix: increase timeout on slow test to avoid flakes

src/localization/locales/en-US.json, src/localization/locales/es-ES.json, src/storyMap/components/StoryMapsHomeCardDefault.js
Correct alt text and links on story maps home card
* alt text was Kobo; is now a description of the image
* link now goes to story maps page, not tools page
=> fix: Correct alt text and links on story maps home card

package-lock.json, package.json, src/config.ts
Just making sure the web client doesn't get too out of step with client shared changes, and that we aren't accidentally breaking the web client without noticing. In draft until https://github.com/techmatters/terraso-client-shared/pull/19 has been merged.
Everything should work exactly the same.
=> chore: bump client shared version

src/landscape/components/LandscapeSharedDataVisualization.test.js, src/sharedData/visualization/components/Visualization.js, src/sharedData/visualization/components/VisualizationConfigForm/AnnotateStep.js
- Fixed drag and drop
- Fixed focus on popup on every key press
Fixes #1150
=> fix: Data map annotate step fixes

src/account/components/AccountLogin.js
Make Google logo monochrome again.
=> fix: make Google logo monochrome

package-lock.json, package.json, src/group/components/GroupSharedDataUpload.js, src/group/components/GroupSharedDataUploadFiles.test.js, src/group/components/GroupView.test.js, src/group/groupFragments.ts, src/group/groupService.ts, src/group/groupSlice.ts, src/landscape/components/LandscapeSharedDataUpload.js, src/landscape/components/LandscapeSharedDataUploadLinks.test.js, src/landscape/components/LandscapeSharedDataVisualization.js, src/landscape/components/LandscapeSharedDataVisualization.test.js, src/landscape/components/LandscapeSharedDataVisualizationConfig.js, src/landscape/components/LandscapeSharedDataVisualizationConfig.test.js, src/landscape/components/LandscapeView.test.js, src/landscape/landscapeFragments.js, src/landscape/landscapeService.js, src/landscape/landscapeService.test.ts, src/landscape/landscapeSlice.js, src/permissions/rules.js, src/sharedData/components/SharedDataCard.js, src/sharedData/components/SharedDataUpload/index.js, src/sharedData/sharedDataService.js, src/sharedData/sharedDataSlice.js, src/sharedData/sharedDataUtils.js, src/sharedData/visualization/components/VisualizationConfigForm/PreviewStep.js, src/sharedData/visualization/components/VisualizationConfigForm/SelectDataFileStep.js, src/sharedData/visualization/components/VisualizationWrapper.js
- Link landscapes directly to shared files, links and visualizations
Fixes #1228 
- https://github.com/techmatters/terraso-backend/pull/904
- https://github.com/techmatters/terraso-client-shared/pull/133
=> refactor: Link landscapes directly to shared files, links and visualizations

src/landscape/components/LandscapeForm/BoundaryStep/OptionDrawPolygon.js
On landscape creation screen, swap layer and draw icons.
Fixes #1282.
=> fix: swap layer and draw icons

src/navigation/components/Navigation.js
Ensure Navigation doesn't exceed 1200px on story maps page.
Fixes #1284.
=> fix: ensure Navigation doesn't exceed 1200px

src/group/components/GroupsHomeCard.js
Ensure consistent text baseline alignment in groups card on home screen between group name and role.
=> fix: ensure consistent text baseline alignment in groups card on home screen

src/storyMap/components/StoryMapForm/TitleForm.js
Center story map title/subtitle placeholders
Fixes #761.
=> fix: center story map title/subtitle placeholders

src/landscape/components/LandscapeMapEmbed.js, src/localization/locales/en-US.json, src/localization/locales/es-ES.json
On embedded landscape map, add link to public landscape profile.
Fixes #863.
=> fix: on landscape map, link to profile

src/common/components/EditableText.js, src/common/components/MiddleEllipsis.js, src/sharedData/components/SharedDataEntryBase.js
Middle truncate long file names in shared files list.
Fixes #1277.
=> fix: middle truncate long file names in shared files list

src/localization/locales/en-US.json, src/localization/locales/es-ES.json, src/sharedData/visualization/components/VisualizationConfigForm.test.js, src/sharedData/visualization/components/VisualizationConfigForm/index.js
- Block navigation after step 1 and unblock after save
- https://github.com/techmatters/terraso-web-client/issues/1231
=> feat: Block navigation in visualization form

src/storyMap/components/StoryMapForm/ShareDialog.js, src/storyMap/components/StoryMapUpdate.test.js
- Fixed owner membership to have separate user field
- https://github.com/techmatters/terraso-web-client/issues/1366
=> fix: Set user field for owner membership in story map

src/localization/locales/en-US.json, src/localization/locales/es-ES.json, src/sharedData/components/SharedResourceDownload.js
For the [file sharing feature](https://github.com/techmatters/terraso-web-client/pull/1451):
* remove extra warning
* updated some strings
=> fix: hide 'no preview' text; update strings

src/group/groupSlice.ts, src/landscape/landscapeSlice.js, src/sharedData/components/SharedDataCard.js, src/sharedData/sharedDataService.js, src/sharedData/sharedDataSlice.js, src/sharedData/visualization/components/VisualizationConfigForm/SelectDataFileStep.js, src/sharedData/visualization/visualizationUtils.js
Renamed sharedData state fields and service functions to avoid confusion between fetching dataEntries and fetching sharedResources
- https://github.com/techmatters/terraso-web-client/issues/1575
=> fix: Renamed state fields and service function names

.gitignore, local.env.sample, package-lock.json, package.json, src/config.ts, src/index.js
Update web client sentry config to ensure data is transmitted. Needed to add `REACT_APP_` prefix to environment variable.
=> fix: update web client sentry config

src/landscape/components/LandscapeForm/BoundaryStepNewBoundariesFile.test.js
When determining the place information by name, [`useIsMounted`](https://github.com/techmatters/terraso-web-client/blob/main/src/landscape/components/LandscapeForm/BoundaryStep/index.js#L158) is called to determine if the boundingBox must be set.
See: [src/landscape/components/LandscapeForm/BoundaryStep/index.js](https://github.com/techmatters/terraso-web-client/blob/main/src/landscape/components/LandscapeForm/BoundaryStep/index.js)
During tests, it was found that `useIsMounted` returns sometimes true, sometimes false. This causes tests to sometimes uses the response from [`getPlaceInfoByName`](https://github.com/techmatters/terraso-web-client/blob/main/src/landscape/components/LandscapeForm/BoundaryStep/index.js#L178-L180), and sometimes to not.
During tests, it seemed that the response …
=> test: mock useIsMounted to prevent intermittently failing tests

src/landscape/components/LandscapeList.test.js, src/landscape/components/LandscapeListMap.js
Opening the landscape list without any existing landscapes caused an error when the map fit to the bounds of all available landscapes. This is because a newly-initialized `LngLatBounds` object is empty and has no defined latitude or longitude. Fix the issue by checking that the bounds is non-empty before passing it to the `fitBounds` method.
Open the landscapes view for an account with no current landscapes. Verify that the page opens successfully without displaying an error.
=> fix: check empty bounds when fitting map to landscape list

src/storyMap/components/StoryMapForm/MapLocationDialog.js
The dialog box was set to not use an 'anchor' for its help icon, which caused it to show in the middle of the screen. I set the component to use default anchor element behavior. This caused a styling issue as a side-effect because non-anchored help boxes are styled differently than anchored ones. I compensated by changing the content to use equivalent styling.
Fixes #1477
Begin creating a new story map. Click 'set map location' and verify that the info dialog is displayed at the expected position with the expected spacing.
=> fix: use anchor for map location dialog, compensate for padding issue

src/home/components/Home.js, src/home/components/Home.test.js, src/tool/components/ToolCard.js
Add fallback page title to Terraso home page when first name is missing.
=> fix: add fallback page title when first name is missing

src/common/components/SocialShare.js, src/monitoring/events.js, src/monitoring/events.test.js, src/navigation/components/Routes.js, src/sharedData/components/SharedDataEntryFile.js, src/sharedData/components/SharedResourceDownload.js, src/sharedData/components/SharedResourceDownload.test.js, src/sharedData/sharedDataHooks.js
Address requests from [Plausible update, analytics updates for the Share Public Link feature #533](https://github.com/techmatters/terraso-product/issues/533). Both download buttons now generate an event, with common code ensuring consistency between the two. Additionally, 'share public link' functionality now uses standardized events as well. Both updated plausible events now live in a common `events.js` file so we can begin centralizing Plausible-related logic with an eye towards having centralized control over all events.
Fixes #533 
Run unit tests where added. Go to downloads for both a group and landscape, press the download button, and verify in the network inspector that the outgoing plausible event calls have the expected parameters.
=> fix: Plausible update, analytics updates for the Share Public Link feature #533

src/navigation/navigationContext.js, src/navigation/navigationContext.test.js, src/sharedData/visualization/components/VisualizationConfigForm/index.js, src/storyMap/components/StoryMapForm/index.js
The navigation blocker as implemented ran into an issue with saving on the map-creation workflow. The form was supposed to navigate to the user's newly-created map on save, but because of how react processes events and state changes, the navigation blocker was still active for the event cycle when the completion callback initiated the new navigation target. This introduces a new capability to the blocker which allows client code to disable the blocking behavior immediately, which allows the navigation to proceed as intended. Also does some minor name refactoring for clarity.
Fixes [1400](https://github.com/techmatters/terraso-web-client/issues/1400)
- Create a new landscape, upload a file, and begin creating a map from it ([as described in original …
=> fix: make nav blocker tool fully disable on form save

src/landscape/components/LandscapeView.test.js, src/sharedData/components/SharedDataEntryBase.js, src/sharedData/components/SharedDataEntryFile.js
In the "Shared Files and Links" section, shared files now display a column with the file extension type.
This addresses GitHub Issue #1551.
Will file some other issues found in the process of looking at this, but not directly related. One on grid layout particulars, one on localization, and one on edit description save button.
1. Go to a landscape and scroll down to the "Shared Files and Links" card
2. Add files if there aren't any already
3. Confirm there is a column for the file extension type, that it displays the correct file extension, that it looks ok on different size screens
- The fileSize and resourceType props are only relevant for SharedDataEntryFile, but the concepts exist in SharedDataEntryBase (previously, there was just one prop that was also only relevant for …
=> feat: Add file extension type column to shared data card for files

src/gis/components/Map.js
Avoid crashing on maps without a source.
Fixes #1336.
=> fix: avoid crashing on maps without a source

src/account/components/AccountLogin.js
Add margin around disclaimer. Aligns text with footer on mobile.
=> fix: add margin around disclaimer

src/localization/locales/en-US.json, src/localization/locales/es-ES.json, src/sharedData/components/SharedDataEntryBase.js
Sets localization properly for the date and author string that was hard-coded into the SharedDataEntryBase component (e.g., "Mar 22, 2024, by Carissa Knipe" in English; "22 mar 2024, por Carissa Knipe" in Spanish) 
Fixes #1662 
See #1662
=> fix: set English and Spanish localization for date and author of shared files

src/sharedData/components/SharedDataEntryBase.js
I incorrectly resolved a merge conflict in https://github.com/techmatters/terraso-web-client/pull/1665.
For a minute the order of shared file info was (incorrectly): file type, then date and user, then file size. 
This change returns the order to: file type, then file size, then date and user.
=> fix: Fix order of shared file info from incorrect merge

src/common/components/ConfirmationDialog.js, src/sharedData/components/SharedDataEntryBase.js, src/sharedData/components/SharedDataEntryFile.js, src/sharedData/components/SharedDataEntryLink.js, src/sharedData/components/SharedFileIcon.js
* vertically align file type icon on mobile
* add space at top of full-screen confirmation dialog
* prevent share icon from overlapping file name on mobile
Fixes #1659.
=> fix: shared files layout improvements

src/landscape/components/LandscapeView.test.js, src/sharedData/components/SharedDataEntryBase.js
Corrects the UUID used in resetProcessing to match the UUID used to set processing. Allows a file to be renamed twice.
Fixes #1661.
=> fix: correct UUID processing state

src/landscape/components/LandscapeView.test.js, src/sharedData/components/SharedDataEntryBase.js, src/sharedData/components/SharedDataEntryFile.js, src/sharedData/components/SharedDataEntryLink.js
Displaying the domain was tied to the `info` prop. The bug was caused when I removed/renamed `info`, such that it then only applied to files, and failed to pass the domain info through for links. 
The `info` concept is now replaced by `InfoComponent` -- whose implementation will differ for files and links, as they will show different info with different layouts.
Fixes #1690 
(which was caused by #1660)
See #1690
=> fix: Display the domain url for links that was previously missing

src/home/components/Home.test.js, src/storyMap/components/StoryMapsCard.js, src/storyMap/components/StoryMapsToolHome.test.js
Don't show edit link for pending maps (will result in 404).
=> fix: don't show edit link for pending maps (will result in 404)

.eslintrc, package-lock.json, src/group/components/GroupList.js, src/landscape/components/LandscapeForm/AffiliationStep.js, src/landscape/components/LandscapeForm/KeyInfoStep.js, src/landscape/components/LandscapeForm/ProfileImageStep.js, src/landscape/components/LandscapeList.js, src/sharedData/visualization/components/VisualizationConfigForm/ColumnSelect.js
Add react/jsx-curly-brace-presence rule to .eslintrc, run linter to enforce style.
We were previously inconsistent in our use.
=> fix: add react/jsx-curly-brace-presence rule to .eslintrc, run linter to enforce style

package-lock.json, package.json, src/common/components/StrictModeDroppable.js, src/group/components/GroupForm.test.js, src/landscape/components/LandscapeForm/AffiliationUpdate.test.js, src/sharedData/visualization/components/VisualizationConfigForm/AnnotateStep.js, src/storyMap/components/StoryMapForm/ChaptersSideBar.js, src/storyMap/components/StoryMapForm/DataLayerDialog.js
remove warnings from tests:
```
Warning: An update to Form inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
act(() => {
/* fire events that update state */
});
/* assert on the output */
```
- [wrap fireEvent in act()
```
Warning: Failed prop type: Invalid prop `disabled` of type `string` supplied to `ForwardRef(Radio)`, expected `boolean`.
```
- ensure disabled is always passed a boolean]
```
Warning: Connect(Droppable): Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead.
```
- use https://github.com/hello-pangea/dnd instead of https://github.com/atlassian/react-beautiful-dnd/
=> fix: remove warnings from tests

src/storyMap/components/StoryMap.js, src/storyMap/components/StoryMapForm.test.js
On chapter exit transition filter layers that are used on the current transition
- https://github.com/techmatters/terraso-web-client/issues/2371
=> fix: Filter layers that used on the current transition

src/account/components/AccountLogin.js, src/localization/locales/en-US.json, src/localization/locales/es-ES.json
Add Terms of Service to the Terraso web app footer and login screen..
Fixes https://github.com/techmatters/terraso-web-client/issues/2518.
=> feat: add TOS to footer and login screen

package-lock.json, package.json, src/gis/gisUtils.js, src/landscape/components/LandscapeSharedDataVisualization.test.js, src/sharedData/visualization/components/VisualizationConfigForm.test.js, src/sharedData/visualization/components/VisualizationConfigForm/VisualizeStep.js, src/sharedData/visualization/components/VisualizationConfigForm/index.js, src/sharedData/visualization/visualizationContext.js
- Hide symbol optiosn if only polygons
- https://github.com/techmatters/terraso-product/issues/562
=> fix: Symbol visualize options, hide symbol options if only polygons

src/storyMap/components/StoryMapForm/ChaptersSideBar.js
Fixes bug where chapters couldn't be changed while a text field had focus.
Fixes #1266
=> fix: blur any active elements when changing chapter focus

package-lock.json, package.json, src/account/components/RequireAuth.js, src/account/components/RequireAuth.test.js
Set hasToken to false if failed to fetch user to avoid re fetching infinite loop
=> fix: Set has token to false if failed to fetch user

src/common/components/Table.js, src/group/components/GroupList.test.js
With a data grid upgrade it seems that the logic to identify sort model changes changed creating a sorting update when the page changes
- https://github.com/techmatters/terraso-web-client/issues/2786
=> fix: Fixed data grid sort model changes tracking

src/App.js, src/navigation/components/Routes.js, src/storyMap/components/StoryMapForm/index.js
Disables the header and footer inside the story maps editor.
No header or footer should be visible inside the story maps editor.
=> feat: full screen storymaps editor
